### ISSUE TITLE
Feedback for SQL

### ISSUE THREAD

**Issue by acipher** [javulorg/javul#1]
Overall looks good except for Activity points that may need the most changes but we can discuss.
Some I didnt check too thoroughly.... I suppose we can check as we go along (as its implemented).

Users table: Need 'geographic location' entry (city, state, country)

Activity points. 
Info from doc:

We also want to keep statistics of all these things, e.g. Users with most activity points (lifetime and last 6 months)
Activity points should be tracked with the unit, for which they apply. For example a user can have 20 activity points in Unit 1, 50 points in Unit 2 and so on. On their user profile, the points are listed with the Unit for which they apply. A total of all activity points is also shown on their user profile.

User profile can show:

```
 Total activity points (last 6 months, lifetime)
 Activity points by Unit:
    Unit 1     10 points
    Unit 2     5 points

[Optional because its not in document]: Display activity points on user profile by activity type e.g.
Task creation: 10 points, Task editing: 5 points
Unit creation: 10 points.


"Need to show users with most activity points" (last 6 months, and lifetime) so ....
Site-wide: 
User 1   100 points (last 6 months)        10 points (lifetime)
User 2    80 points                   5
```

**Anant: how do you counting last 6 months 100 points and lifetime 10 point? I am assuming lifetime points as sum of all points for that user since he started to the time it calculated.**

***Ed: We can remove the 6-months requirement and just do the lifetime points (you are right, its the total points since account creation). I might think about the 6-months feature again in the future and if people are using the site at the time, I'll ask them what they want. For reference, I searched "database auto expiring records" and there was a discussion here: http://stackoverflow.com/questions/26046816/is-there-a-way-to-set-an-expiry-time-after-wich-a-data-entry-is-automatically . I think that means activity points would need to be tracked by date. So there would be a table for each user, with two fields: activity_points, and date. For example 5 points, earned on 5/19/2016. But yes, for now we can just do the total points since account creation.

[Optional because its not in document]
 On Unit home pages:
    Most Active users last 6 months, lifetime
    User 1,  100, 50
    User 2,  50,  10

You can see if any updates are needed for the Activity table data, to make the above possible (excluding items marked as Optional). Its ok to duplicate data if that means we will have faster DB queries for display purposes.

Archive tables ..? (to store deleted items). Can be duplicate of 'main' tables, but just '_archived' in the table name.

**Anant: we will use laravel soft delete feature for this. No need to have separate tables.**
***Ed: Ok great.

objective_importance_level ...
(I couldnt understand why user_id is there in the new objectives_importance table..?)
 can be merged to main objectives table, and that table can be deleted?
   importance_level int(10)    (initial value=1)

**Anant: we need to track "+1" of each user so to track that its taken as separate table. How do you thinking to track them by user if we take it in to main objectives table? I assume you are asking to update field to +1 everytime user upvote. Let me know if I misunderstood.**  
**\* Ed: You're right, we need to track the +1 to the user so it can only be done once. So you can keep your implementation for this and also the table below. I have no other comments on the DB for now, so everything looks good and ready. We can make updates to the DB later as needed.

Similar for issues_importance table, can be merged I think.

**Anant: This is also same for above. We can still make single table merge objectives and issue importance_level tables by flag field e.g. objective, issue**

tasks Table:
user completing the task will get activity points in all cases (even if $ reward is present)

**Comment by javulorg** [comment]
Closed for now. Will re-open in the future if needed.
