### ISSUE TITLE
Unit/User Update: Issues for Location

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#10]
The items below talk about Units. These Location items also apply to updates for User account updates as Users can also set locations for their accounts.

1. If a Unit with the location "Global" is created, and saved, and then Updated, it asks to fill out certain fields (city, state).

Suggestion: 
- Only do these checks if the field was changed
-  Dont require city/state for Global on Update also and gray out these two fields (just like how it happens for Unit create)

2. When Global Unit is created and its City/state is changed to some country/state, the form is still in an error state:
![image](https://cloud.githubusercontent.com/assets/19337355/21290798/3cd2e89c-c496-11e6-913f-da5629a7f860.png)

Steps to reproduce:
- Create a test unit of Global location
- Edit the unit and change its country, city and state. Edit should work and allow the update.

3.  Some states do not have cities. In that case it wont let me save the item. Solution: Allow save if city does not exist and Use State name for the Location. Example: Austria (country) -> Upper Austria

**Comment by acipher** [comment]
It should be fix. Can you please review? 

Let me know if need to change.

**Comment by javulorg** [comment]
Thanks, closed.

**Comment by javulorg** [comment]
Actually, that issue is fixed however when I use 'global' as a location, it doesn't show up in the Location field. 
![image](https://cloud.githubusercontent.com/assets/19337355/23531977/1bbdc4c6-ff77-11e6-9546-4e616e46d3e2.png)
Steps to reproduce: Create any unit with Global location and save.

I see the same if I choose Austria as country and Upper Austria as State. When deciding what to display you can use this kind of algorithm:
If "country" = global then 
    display = country
else if city = (not blank) then
    display = city
else if state= (not blank) then
    display = state
else 
   display = country
end if

**Comment by acipher** [comment]
Shown "Global" in UNIT LOCATION field for unit in which user selected "GLOBAL" as country.

Can you please check it again?

**Comment by javulorg** [comment]
Thanks, closed.
