### ISSUE TITLE
Activity Log bar is displayed out of the Activity Log layout box.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#100]
Environment :- Windows 7
Module :- My Profile / User Wiki
Credentials :- r6.pulsefbi@gmail.com
Priority :- Low

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Click on MyProfile and scroll down and observe.
3.Navigate to home page and click on Units and Scroll down and observe.
4.Navigate to home page and click on My Contributions and Scroll down and observe.

Actual Result :- Activity Log bar is displayed out of the Activity Log layout box.
Expected Result :- Activity Log bar should not be displayed out of the Activity Log layout box.

Screenshots :- 
![javul - activity log - 20190204-161938](https://user-images.githubusercontent.com/7206531/52206191-7935f080-289f-11e9-8124-df4073fd920d.png)
![javul - activity log - 20190204-145311](https://user-images.githubusercontent.com/7206531/52206192-7935f080-289f-11e9-91d5-a4d881325d3c.png)
![javul - activity log - 20190204-144824](https://user-images.githubusercontent.com/7206531/52206194-7935f080-289f-11e9-8193-2b7c1a3d4707.png)

**Comment by acipher** [comment]
Fixed.
Screenshots :-
![my_contributions](https://user-images.githubusercontent.com/3071346/52616133-72ba0100-2ebd-11e9-9e8a-1416b67bfc47.png)
![unit info view](https://user-images.githubusercontent.com/3071346/52616134-72ba0100-2ebd-11e9-9ed3-95df1f3118d3.png)
![user profile](https://user-images.githubusercontent.com/3071346/52616135-72ba0100-2ebd-11e9-985f-29ad0e45204b.png)
