### ISSUE TITLE
 "The username already exist in system" error message is displaying when user enters space in user name text field and click on signup

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#102]
Environment :- Windows 7
Module: sign up
Credentials :-john_k@mailinator.com/11111111
priority :High

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page.
3. Click on signup
4 Enter  space in user name field
5 Click on sign up
6 Observe

Actual result: "The username already exist in system" error message is displaying when user enters space in user name text field and click on sign up.
Expected result: "The username already exist in system" error message should not be displayed. 

Video URL :https://drive.google.com/file/d/1iJ3hFdIEPVBHqxfn2xMcyvN8rIijXS3f/view?usp=sharing

**Comment by acipher** [comment]
Fixed please check and review.
