### ISSUE TITLE
Number of users Logged in are not displayed. 

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#103]
Environment :- Windows 7
Module :- Home Page
Credentials :- r6.pulsefbi@gmail.com
Priority :- Low

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Scroll down and observe 'Logged In'.

Actual Result :- Number of users Logged in are not displayed. 
Expected Result :- Number of users Logged in should be displayed. 

Screenshot :- 
![javul - home page - 20190204-171948](https://user-images.githubusercontent.com/7206531/52206850-7f2cd100-28a1-11e9-83a2-b51082979cf4.png)

**Comment by acipher** [comment]
Done please check and review.
