### ISSUE TITLE
When clicked on 'Terms of Service' and 'Disclaimer', same page is displayed.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#104]
Environment :- Windows 7
Module :- Terms of Service / Disclaimer
Credentials :- r6.pulsefbi@gmail.com
Priority :- High

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to Home page.
3.Click on 'Terms of Service' and observe.
4. Click on 'Disclaimer' and observe.

Actual Result :- When clicked on 'Terms of Service' and 'Disclaimer', same page is displayed.
Expected Result :- When clicked on 'Terms of Service' and 'Disclaimer', particular page should be displayed.

Video URL :- https://drive.google.com/file/d/1sIz7SC-PsVJHobq-9gM-5YSoOr2NIBla/view?usp=sharing

**Comment by javulorg** [comment]
Moved into #105
