### ISSUE TITLE
Wiki links not viewable by anonymous users

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#106]
Steps to reproduce :-
1. Open Javul Site: www.javul.org
2. If logged in, log out and go to home page again: www.javul.org
3. Go to demo Unit page: http://www.javul.org/units/l0kmVNmDn5/hardware
4. Click on "Wiki". Link requires a login.
5. Click on an individual wiki page e.g.: http://www.javul.org/wiki/qdQJNqgr83/4/software_testing
This also needs a login.

**Comment by acipher** [comment]
As on your explanation do i need make wiki page viewable to all users and anonymous users?.
Can you please confirm.

**Comment by javulorg** [comment]
Also applicable for Forum links: http://www.javul.org/forum/p29JPnmAZ4
And a main Wiki page: http://javul.org/wiki/home/qdQJNqgr83/software_testing

**Comment by acipher** [comment]
Now anonymous user can able to view of wiki page.
[Wiki links working](https://drive.google.com/file/d/1avwekWD_nxrg9WvxL1UaPZPgnKwNmgZN/view?usp=sharing)
For the Forum links **we need logged in user id** that's why we can not able to make viewable to anonymous user please confirm @javulorg

**Comment by javulorg** [comment]
I would like to show forum links for anonymous users. 'Not logged in' can be used in places which require the display of the logged-in user.

**Comment by acipher** [comment]
Now anonymous user can able to view forum link can you please check and review. Please check below attachment.
[https://www.screencast.com/t/2KmOIGfobFU](https://www.screencast.com/t/2KmOIGfobFU)

**Comment by javulorg** [comment]
Thanks! Closing this.
