### ISSUE TITLE
Comment box is displayed to anonymous users

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#107]
Steps to reproduce:
1. Logout of site and go to demo objective:  http://www.javul.org/objectives/WA53drwD86/software
2. Observe that Comment box is viewable
3. Similarly for demo Task: http://www.javul.org/tasks/nx5vOr2z7a/learning_sdlc
4. Please also check for a demo Issue.

Desired behavior: Existing comments should be displayed. 'Login to Comment' link should be displayed instead of the Comment box

**Comment by acipher** [comment]
Can you please specify which places i have need to change comment box change.

**Comment by javulorg** [comment]
I think you got all of them. Thanks, closing this.
