### ISSUE TITLE
When invalid credentials are entered, Page is refreshed without displaying any Error message.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#108]
Environment :- Windows 7
Module :- Login
Credentials :- r6.pulsefbi@gmail.com
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and navigate to login page.
2.Enter invalid credentials and click on Login.
3.Observe.

Actual Result :- When invalid credentials are entered, Page is refreshed without displaying any Error message.
Expected Result :- When invalid credentials are entered, Error message should be displayed as "Invalid Username/Password entered".

Video URL :- https://drive.google.com/file/d/1Td7DRUlskc4id9jNpFy65kLGZknL-g9g/view?usp=sharing

**Comment by acipher** [comment]
Done please check and review.
