### ISSUE TITLE
(*) Symbol is not displaying) all the mandatory fields should be highlighted without entering any fields when the user clicks on submit.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#109]
Environment :- Windows 7
Module: Sign up
Credentials :john_k@mailinator.com/11111111]
Priority :Normal

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page
3. Click on signup
4.Click on submit with out entering any details
5. Observe
Actual result: (*) Symbol is not displaying) all the mandatory fields should be highlighted without entering any fields when the user clicks on submit.
Expected result: (*) symbol should be display for all mandatory fields.

Video URL: https://drive.google.com/open?id=17C4OKssbyEG3vqNM7OsCmbiJQnELm2IH

**Comment by acipher** [comment]
Added required fields with (*) on placeholder. Please review.
