### ISSUE TITLE
When clicked on Create Task, Page is refreshed and all the data entered are cleared automatically, without displaying any error message.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#110]
Environment :- Windows 7
Module :- Tasks
Credentials :- r6.pulsefbi@gmail.com
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Tasks.
3.Click on Create Task.
4.Select valid Unit, Objective, Task skills, From/To Date-Time.
5.Enter valid data in Task name, Compensation and in Summary field. 
6.Don't enter anything in remaining fields and click Create Task.
7.Observe.

Actual Result :- When clicked on Create Task, Page is refreshed and all the data entered are cleared automatically, without displaying any error message.
Expected Result :- When clicked on Create Task, Page should not be refreshed and all the data entered should not be cleared, Error message message should be displayed.

Video URL :- https://drive.google.com/file/d/1J89O_XFDmYdYBVEKZgqczLsMIzqzBd0z/view?usp=sharing

**Comment by acipher** [comment]
Fixed showing proper validation message at all required field.
