### ISSUE TITLE
No validation message is displaying while signup

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#111]
Environment :- Windows 7
Module: sign up
Credentials :- john_k@mailinator.com/11111111
priority :Normal

Steps to reproduce :-
1.Open Javul Site
2 .click on signup
4.Enter existing user name
5 enter existing email
6 observe
Actual result:No validation message is displaying while signup,but after submitting its displaying error message.

Expected result: validation message should be display when user enters existing email.

Video URL:https://drive.google.com/file/d/1U1TmK_jqklIOHNjpFctQox3DTp-gYtL7/view?usp=sharing

Screenshot URL:https://drive.google.com/file/d/1qhsjEPzXbsMi9ftI1UkMZfZNmftAwyxk/view?usp=sharing

**Comment by acipher** [comment]
After submission it already shows email existing error. see attached. @javulorg can you validated this?

![image](https://user-images.githubusercontent.com/3071346/53680047-9bcef400-3cfb-11e9-9203-5f0f24072e97.png)

**Comment by javulorg** [comment]
I see what he meant. The username is checked 'live' before hitting the Submit button. Can the check for the email be 'live' also, like it is for the username?

**Comment by acipher** [comment]
Added validation for email same as username.
