### ISSUE TITLE
Without selecting any file, when clicked on cancel, Uploaded file is removed automatically.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#112]
Environment :- Windows 7
Module :- Tasks
Credentials :- r6.pulsefbi@gmail.com
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Tasks.
3.Click on Add Task.
4.Scroll down and Click on Select File under Documents.
5.Select a valid file and click on Open. 
6.Again click on Change and Click on cancel and observe.

Actual Result :- Without selecting any file, when clicked on cancel, Uploaded file is removed automatically.
Expected Result :- Without selecting any file, when clicked on cancel, Uploaded file should not be  removed.

Video URL :- https://drive.google.com/file/d/1oZy6cl3ZTvqUS4x8KJv3Q8Tc547OyW3b/view?usp=sharing

**Comment by acipher** [comment]
@javulorg  fixed as described on above comment please check and review.

**Comment by javulorg** [comment]
I assume it works, thanks.
