### ISSUE TITLE
 Compensation amount text field is accepting infinite amount

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#113]
Environment :- Windows 7
Module: Units
Credentials : john_k@mailinator.com/11111111
Priority :-Normal

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page
3.Click on units
4.Click on existing created unit
5 Click on ADD task
6 It will navigate to create Task page
7 Enter infinite amount in Compensation text field
8 Observe

Actual result: Compensation amount text field is accepting infinite amount

Expected result: Compensation amount text field should not accept infinite amount.

video URL:https://drive.google.com/file/d/1A9R7pcnx8IcOp_dO1ZvdiJH6IIb23Whk/view?usp=sharing

**Comment by javulorg** [comment]
Similar to #132

**Comment by acipher** [comment]
Limited amount entry to 10 digits. Please review
