### ISSUE TITLE
While creating Tasks, even after selecting Task Skills, error message is displayed as "The task skills field is required."

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#114]
Environment :- Windows 7
Module :- Tasks
Credentials :- [r6.pulsefbi@gmail.com](mailto:r6.pulsefbi@gmail.com)
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Tasks.
3.Click on Add Task.
4.Without entering any thing, Click on Create Task.
5.Enter valid data in all the highlighted mandatory fields and click on Create Task.
6.Now again enter valid data in same mandatory fields and select Task Skills. 
7.Click on Create Task and observe.

Note :- User has not selected "To Date", but error message is displayed for "Task Skills".

Actual Result :- While creating Tasks, even after selecting Task Skills, error message is displayed as "The task skills field is required."
Expected Result :- While creating Tasks, after selecting Task Skills, error message should not be displayed as "The task skills field is required."

Video URL :- https://drive.google.com/file/d/1XrNjLM2q5Ihf9Hu3Fd0OYPT72DYcMaOK/view?usp=sharing

**Comment by acipher** [comment]
Fixed please review.
