### ISSUE TITLE
"Planning and organising" skill is overlapping on the browse button in task skills text field

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#115]
Environment :- Windows 7
Module: Units
Credentials :-john_k@mailinator.com/11111111
priority :Normal

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page
3.Click on units
4.Click on existing created unit
5 Click on ADD task
6 It will navigate to create Task page
7 In task skill text field(browse)select Planning and organising 
8 Observe

Actual result: "Planning and organising" skill is overlapping on the browse button in task skills text field.
 
Expected result: "Planning and organising" skill should not overlap.

video URL: https://drive.google.com/file/d/1VKDyDSn_lgpETSKdVv7oU-6dGLgS4JPs/view?usp=sharing

**Comment by acipher** [comment]
Added more space to "Task Skills" so that it can cover up. Should be fixed. Please review.
