### ISSUE TITLE
While creating Tasks, after entering valid data in all the mandatory fields, user is still not able to create new Task and error message is also not displayed.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#116]
Environment :- Windows 7
Module :- Tasks
Credentials :- [r6.pulsefbi@gmail.com](mailto:r6.pulsefbi@gmail.com)
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Tasks.
3.Click on Add Task.
4.Select valid Unit, Objective, Task Skills,From/ To Date and enter valid data in Task name. 
5.Don't enter anything in remaining fields and Click on Create Task and observe.

Actual Result :- While creating Tasks, after entering valid data in all the mandatory fields, user is still not able to create new Task and error message is also not displayed.
Expected Result :- While creating Tasks, after entering valid data in all the mandatory fields, user should be able to create new Task and if not able to create, then valid error message should be displayed.

Video URL :- https://drive.google.com/file/d/1QKRUppli7w5seiRkQynmncJCZ_U2FPhF/view?usp=sharing

**Comment by acipher** [comment]
This issue fixed on #110 please check and review.
