### ISSUE TITLE
"Whoops, looks like something went wrong." ErrorException an error message is displaying when user tries to edit issue information.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#117]
Environment :- Windows 7
Module: Issues
Credentials :- john_k@mailinator.com/11111111
priority :Major

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page
3.Click on issues
4.Click on existing created issues
5 It will redirect to issue information
6 Click on edit
7 Observe

Actual result: "Whoops, looks like something went wrong." ErrorException an error message is displaying when user tries to edit issue information.
Expected result: When user click on edit issue information, error message should not be displayed.

video URL: https://drive.google.com/file/d/1Ck4U31ObRTP5jxxuvbcdgz5vI64aKzAU/view?usp=sharing

**Comment by acipher** [comment]
Fixed please check and review.
