### ISSUE TITLE
Task completion ratings(in wiki user) is user editable it should be displayed as starts(***)

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#119]
Environment :- Windows 7
Module: Issues
Credentials :- john_k@mailinator.com/11111111
priority :Major

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page
3.Click on My profile
4.Observe ratings is displaying correct way
5.Now click on user wiki new page
6.Observe ratings is user editable,its not displaying as starts
 
Actual result: Task completion ratings(in wiki user) is user editable it should be displayed as starts(***)
Expected result: Task completion ratings should not be user editable,it should displayed as starts

**Comment by acipher** [comment]
Fixed please check and review.
