### ISSUE TITLE
Global Statistics: Logged in users

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#12]
At bottom of the site for all pages, “Logged in” should show the number of users currently logged in to the site. Something like this can be used: send a 30 second ping to check if the user still has a Window open with the Javul URL.

**Comment by acipher** [comment]
Shown total logged in user into system and sended ping after every 30 seconds to check if user still has a window open.

Please review.

**Comment by javulorg** [comment]
Thanks, closed.
