### ISSUE TITLE
Without entering any data, when clicked on "Submit Comment", error message is displayed as "Something Went Wrong, Try Again".

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#120]
Environment :- Windows 7
Module :- Objectives / Comment
Credentials :- [r6.pulsefbi@gmail.com](mailto:r6.pulsefbi@gmail.com)
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Objectives and select any objective.
3. Without entering any data, click on Submit Comment and observe.

Actual Result :- Without entering any data, when clicked on "Submit Comment", error message is displayed as "Something Went Wrong, Try Again".
Expected Result :- Without entering any data, when clicked on "Submit Comment", mandatory field should be highlighted and validation/error message for that field should be displayed..
"Something Went Wrong, Try Again" error message should not be displayed.

Video URL :- https://drive.google.com/file/d/1BSqKxYOlHHaPadCssho675jQNnS-g-ke/view?usp=sharing

**Comment by acipher** [comment]
Showing proper validation message when user click on "Submit Comment".
Please check and review.
