### ISSUE TITLE
User-1 is able to modify and update User-2's units, objectives, tasks.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#121]
Environment :- Windows 7
Module :- Objectives / Comment
Credentials :- User-1 :-  [r6.pulsefbi@gmail.com](mailto:r6.pulsefbi@gmail.com)
User-2 :- john_k@gmail.com
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Units and select other user(user-2).
3.Select any active unit and modify the data.
4. Click on Update Unit and observe.

Actual Result :- User-1 is able to modify and update User-2's units, objectives, tasks.
Expected Result :- User-1 should not be able to modify and update User-2's units, objectives, tasks.

Video URL :- https://drive.google.com/file/d/162jG_hcqC3-pcCNoXr1fMGcp7Cr0M7CN/view?usp=sharing

**Comment by javulorg** [comment]
This is working as intended. All tasks, objectives and unit's can be edited by anyone.
