### ISSUE TITLE
Under Global activity log/issues,hours information is not displayed in the same line(4 is displayed out of the line).

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#122]
Environment :- Windows 7
Module: Issues
Credentials :- [john_k@mailinator.com]/11111111
priority :Normal

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page
3.Click on issues
4. under Global activity log/issues, observe hours information is not displayed in the same line(4 is displayed out of the line).

Actual result: Under Global activity log/issues,hours information is not displayed in the same line(4 is displayed out of the line).

Expected result: "Global activity log/issues",hours information should be displayed in same line. 

Screen shot :  https://drive.google.com/file/d/1LrTkvJ2muUKjJBB5-fHqkV0mCjlyjotq/view?usp=sharing

**Comment by acipher** [comment]
Should be fixed. Please review.
