### ISSUE TITLE
'Assigned To' field is displayed, but there is no option displayed to Assign a task to any user.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#123]
Environment :- Windows 7
Module :- Tasks
Credentials :- [r6.pulsefbi@gmail.com](mailto:r6.pulsefbi@gmail.com)
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Tasks and Observe that Assign To field is empty for all the tasks.
3.And while creating or editing the task, there is no option displayed to assign the task to any user.

Actual Result :- 'Assigned To' field is displayed, but there is no option displayed to Assign a task to any user.
Expected Result :- If 'Assign To' field is displayed, then there should be an option displayed to assign the task to any user.

Video URL :- https://drive.google.com/file/d/1IDMaHepRX0ZcZTScfr3KsdPbX0NLbfEs/view?usp=sharing

**Comment by acipher** [comment]
@javulorg can you please validate the issue?, If it's valid can you please explain?

**Comment by javulorg** [comment]
@acipher, this can be closed as long as there's a way to assign a user to a task after they have bid on it. Looking at the original job description:

_> Awaiting Assignment:  The task is now waiting for other users to assign the task to one of the bidders. When the task is assigned the task status becomes …

> Assigned:  The user who got the task awarded, is asked to confirm that they accept the task. They have a “My Tasks” link which shows them information about the tasks they are involved in (for creating, editing, bidding, work in progress, completed etc). 
‘Assigned‘ shows them the tasks they have been assigned. When a task has been assigned, they are shown a prompt that asks them if they accept the assignment._

So as long as the above is true and it works, we can close this ticket.
