### ISSUE TITLE
"404 Page not found" an error message is displaying when user clicks on "skills".

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#126]
Environment :- Windows 7
Module: Tasks
Credentials :- [john_k@mailinator.com]/11111111
Priority :Major

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page
3.Click on tasks
4 Now clicks on skills
5 Observe

Actual result: "404 Page not found" an error message is displaying when user clicks on "skills".

Expected result: particular page should be displayed, instead of displaying "404 Page not found" an error message.
Video URL: https://drive.google.com/file/d/1NHoaSAUvB4DopI4Xvzz3_fg5tbiGthlx/view?usp=shar

**Comment by acipher** [comment]
I cannot able to view above video link and can you please check.

**Comment by acipher** [comment]
@javulorg can you please tell us what we can show when user click on any particular skill?

**Comment by javulorg** [comment]
Ah yes, any click on a skill should show a page listing all the Tasks that have that skill. This way a user who has a certain skill can find other tasks that require that same skill.

**Comment by acipher** [comment]
Showing task list with selected task skill, @javulorg can you please check and review.

![image](https://user-images.githubusercontent.com/3071346/54414652-d84d1780-471f-11e9-9e3c-2983f370faf1.png)

**Comment by javulorg** [comment]
Closing.
