### ISSUE TITLE
When user click on 'Bid Now', it's not working. Page is refreshed.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#127]
Environment :- Windows 7
Module :- Tasks
Credentials :- johnCarter@mailinator.com
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Tasks.
3.Click on 'Bid Now' of any task and observe.

Actual Result :- When user click on 'Bid Now', it's not working. Page is refreshed.
Expected Result :- When user click on 'Bid Now', it should be working.

Video URL :- https://drive.google.com/file/d/11fSRibP3zd871GeWsQZUN-h3mQ8T1hd7/view?usp=sharing

**Comment by acipher** [comment]
Unable to reproduce. I can able to. Is there any special case? @javulorg can you please validate?

**Comment by javulorg** [comment]
Works for me also, however could you add the "Bid now" button to the Task page also? For example: http://www.javul.org/tasks/0Pr9eovjDM/test_task_3
It can be added next to "Open For bidding" text.
And then this can be closed.
We'll revise the 'bid now' page at some point later.

**Comment by acipher** [comment]
**Bid Now** Button added on task view page.
![image](https://user-images.githubusercontent.com/3071346/54007466-eb903e00-4187-11e9-8e13-3537406f3188.png)
