### ISSUE TITLE
"No Record Found" is displayed for 'Objectives details', but for 'Units Details' and 'Tasks details', nothing is displayed.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#128]
Environment :- Windows 7
Module :- My Profile
Credentials :- [johnCarter@mailinator.com](mailto:johnCarter@mailinator.com)
Priority :- Normal

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on My Profile.
3.Click on 'Units Details' and observe.
4.Click on 'Objectives Details' and observe.
5.Click on 'Tasks Details' and observe.

Actual Result :- "No Record Found" is displayed for 'Objectives details', but for 'Units Details' and 'Tasks details', nothing is displayed.
Expected Result :- "No Record Found" should be displayed for 'Objectives details', 'Units Details' and 'Tasks details', if there aren't any records created yet. 

Screeshots :- 
![javul - my profile - objectives details - 20190206-112600](https://user-images.githubusercontent.com/7206531/52323380-d8f8dc80-2a02-11e9-9656-a9e918bb6d96.png)
![javul - my profile - tasks details - 20190206-112618](https://user-images.githubusercontent.com/7206531/52323381-d8f8dc80-2a02-11e9-9fc0-9e9731e499de.png)
![javul - my profile - unit details - 20190206-112543](https://user-images.githubusercontent.com/7206531/52323383-d9917300-2a02-11e9-811f-0ea77ac852d1.png)

**Comment by acipher** [comment]
Should be fixed now. Please review.
