### ISSUE TITLE
Confirmation message is not displaying when user edit the "objectives"

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#129]
Environment :- Windows 7
Module: Objectives
Credentials :- [john_k@mailinator.com]/11111111
Priority :Normal

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page
3.Click on Objectives
4. Click on existing objectives
5. Click on edit
6 Do some changes
7 Click on Update Objectives
8 Observe 
('Your details have been saved' confirmation message is not displaying.). 

Actual result: Confirmation message is not displaying when user edit the "objectives"
Expected result: Confirmation message should be displayed when user edit the "objectives"

 Video URL:  https://drive.google.com/file/d/1NHoaSAUvB4DopI4Xvzz3_fg5tbiGthlx/view?usp=sharing

**Comment by acipher** [comment]
Done please check and review.
![image](https://user-images.githubusercontent.com/3071346/53936100-be338980-40ce-11e9-9e09-4eea7bf2751a.png)
