### ISSUE TITLE
Javul uses zCash, but paypal option is displayed.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#130]
Environment :- Windows 7
Module :- Add Fund
Credentials :- [johnCarter@mailinator.com](mailto:johnCarter@mailinator.com)
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Objectives and select any objective.
3.Click on Add(+) icon of Funds and observe.

Actual Result :- Javul uses zCash, but paypal option is displayed.
Expected Result :- Javul uses zCash, so paypal option should not be displayed.

Defect Video URL :- https://drive.google.com/file/d/1zPcy_89gxByNy87eH7tQ-QK9PxtPmjOC/view?usp=sharing

**Comment by acipher** [comment]
Fixed please check below image.

![image](https://user-images.githubusercontent.com/3071346/54423120-eb6ae200-4735-11e9-8d9c-dd96ab85510c.png)
