### ISSUE TITLE
Amount  field is accepting infinite amount.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#132]
Environment :- Windows 7
Module: Objectives
Credentials :- [john_k@mailinator.com]/11111111
Priority :Major
Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Objectives and select any objective.
3.Click on Add(+) icon of Funds and enter the infinite amount in amount field.
4 Observe.

Actual result: Amount  field is accepting infinite amount.
Expected result: Amount  field should accept the amount  within the range, and range validation message should be displayed for amount field.
 Video URL: https://drive.google.com/file/d/1ovpXKfY8US3gDEZmvyytv2sCMIwiPcFU/view?usp=sharing

**Comment by javulorg** [comment]
Similar to #113

**Comment by acipher** [comment]
Limited amount entry to 10 digits. Please review
