### ISSUE TITLE
When user try to "Transfer Amount from Unit", error message is displayed as "Something Went Wrong, please try Again".

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#133]
Environment :- Windows 7
Module :- Add Fund
Credentials :- [johnCarter@mailinator.com](mailto:johnCarter@mailinator.com)
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Objectives and select any objective.
3.Click on Add(+) icon of Funds and enter the valid amount in amount field.
4.Click on 'Transfer Amount from Unit' and observe.

Actual Result :- When user try to "Transfer Amount from Unit", error message is displayed as "Something Went Wrong, please try Again".
Expected Result :- When user try to "Transfer Amount from Unit", error message should not be displayed.

Defect Video URL :- https://drive.google.com/file/d/1iHsiFsj5oXko9bKsZjtgIeS9TogfFKpI/view?usp=sharing

**Comment by acipher** [comment]
Fixed showing relevant message please check below image.
![image](https://user-images.githubusercontent.com/3071346/54665620-9223f980-4b0d-11e9-8253-eb097ad37a7c.png)
