### ISSUE TITLE
'Account Creation' and 'Confirmation Email' is set to 'ON', Once user logout and login, by default, 'Account Creation' and 'Confirmation Email' is set to 'OFF'.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#134]
Environment :- Windows 7
Module :- Account Settings
Credentials :- [johnCarter@mailinator.com](mailto:johnCarter@mailinator.com)
Priority :- Normal

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Account Settings and select 'Alert Settings'.
3.Switch on 'Account Creation' and 'Confirmation Email' and save profile.
4.Logout and login again.
5.Navigate to 'Account settings' and select 'Alert settings' and observe.

Actual Result :- 'Account Creation' and 'Confirmation Email' is set to 'ON', Once user logout and login, by default, 'Account Creation' and 'Confirmation Email' is set to 'OFF'.
Expected Result :- When 'Account Creation' and 'Confirmation Email' is set to 'ON', Then , even when user logout and login, 'Account Creation' and 'Confirmation Email' should be set to 'ON'.

Defect Video URL :- https://drive.google.com/file/d/1ZcPGXfzee7doaEVQC838IcdGewdOYHzY/view?usp=sharing

**Comment by acipher** [comment]
Can you please check ticket #90 and confirm with @javulorg.

**Comment by javulorg** [comment]
hi Anant, this can be closed along with #90 since those options were removed.
