### ISSUE TITLE
When user try to upload broken image, error message is displayed as "Internal Server Error".

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#135]
Environment :- Windows 7
Module :- Account Settings
Credentials :- [johnCarter@mailinator.com](mailto:johnCarter@mailinator.com)
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Account Settings.
3.Click on 'Drag & drop files here' to add profile picture.
4.Select broken image and observe. 

Actual Result :- When user try to upload broken image, error message is displayed as "Internal Server Error".
Expected Result :- When user try to upload broken image, error message should not be displayed as "Internal Server Error". It should be displayed as "Error, while uploading broken image".

Defect Video URL :- https://drive.google.com/file/d/1zYAUZMpXWZ17Mox-Vb7Rv31UBxYplXSB/view?usp=sharing

**Comment by acipher** [comment]
Now user cannot able to upload broken image it show error message **No files were processed**. Please see attachment.

[https://drive.google.com/file/d/1hd0FFI02ytdmGeSFZt2yo8DBlvghE7yz/view?usp=sharing](https://drive.google.com/file/d/1hd0FFI02ytdmGeSFZt2yo8DBlvghE7yz/view?usp=sharing)
