### ISSUE TITLE
"No result found" message is not displaying when user enters space in search fields.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#136]
Environment :- Windows 7
Module: Units
Credentials :- [john_k@mailinator.com]/11111111
Priority :Normal

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2. Clicks on tasks
3 Go to search by skills>Enter space 
4 Observe no result found message is displaying
5 Now go to search by status> enter space 
6 Observe "no result found" message is not displaying.

Actual result:  "No result found" message is not displaying when user enters space in search fields.
Expected result: "no result found" message should be displayed when user enters space in  search fields. 

 Video URL: https://drive.google.com/file/d/1VGi0Wahxi678uFuuVvV6FNrQYpzP5xQi/view?usp=sharing

**Comment by acipher** [comment]
Fixed please check and review.
![task search by status](https://user-images.githubusercontent.com/3071346/53935117-36984b80-40cb-11e9-86a2-ddfd9d6ae595.png)
