### ISSUE TITLE
When user click on 'View Forum Thread', same page is displayed.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#137]
Environment :- Windows 7
Module :- Objectives
Credentials :- [johnCarter@mailinator.com](mailto:johnCarter@mailinator.com)
Priority :- Normal

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Objectives and select any objective.
3.Click on 'View Forum Thread' and observe.

Actual Result :- When user click on 'View Forum Thread', same page is displayed.
Expected Result :- When user click on 'View Forum Thread', same page should not be displayed. Particular page should be displayed.

Defect Video URL :- https://drive.google.com/file/d/1O-xirLVmGfrBdnnFmfDO4FP9VL3RjpS5/view?usp=sharing

**Comment by acipher** [comment]
Should be fixed now. Please review.
