### ISSUE TITLE
When user create units (objectives,tasks,issues) invalid time is displayed.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#138]
Environment :- Windows 7
Module: Units
Credentials :- [john_k@mailinator.com]/11111111
Priority :Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2. Create units( objectives,tasks,issues)
3 Observe in GLOBAL ACTIVITY LOG invalid time is displaying.
{When user create units (objectives,tasks,issues) one min ago but its displaying 5 hourds ago in GLOBAL ACTIVITY LOG].

Actual result: When user create units (objectives,tasks,issues) invalid time is displayed.
Expected result: Proper time should be displayed When user create units (objectives,tasks,issues).

 Video URL:
https://drive.google.com/file/d/1Mpt6oYYU7KVuEuWeE34Y-m_5MirG-xjz/view?usp=sharing

**Comment by acipher** [comment]
It's work for me can you please check below image.

![image](https://user-images.githubusercontent.com/3071346/54472142-b15b1800-47e9-11e9-9edc-ff18e5e6b978.png)


@javulorg can you please validate?

**Comment by javulorg** [comment]
Worked for me too, closing.
