### ISSUE TITLE
When user open Login Page, "Connection is not secure" is displayed.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#139]
Environment :- Windows 7, Mozilla Firefox Browser
Module :- Login
Credentials :- [johnCarter@mailinator.com](mailto:johnCarter@mailinator.com)
Priority :- Normal

Steps to reproduce :-
1.Open Javul Site. 
2.Click on Login and observe.

Actual Result :- When user open Login Page, "Connection is not secure" is displayed.
Expected Result :- When user open Login Page, "Connection is not secure" should not be
 displayed.

Screenshot :- 
![javul - login](https://user-images.githubusercontent.com/7206531/52332714-837ff800-2a21-11e9-8402-6744118d1b44.png)

**Comment by acipher** [comment]
This is because we do not have SSL installed. @javulorg can you review this?

**Comment by javulorg** [comment]
hi Anant, I guess it would be a good thing to install an SSL certificate. When I search ""linode installing ssl", I found this video: https://www.youtube.com/watch?v=JciwYHqtJm4
Looking at the youtube comments it looks like it was easier following the directions there compared to other sources. I hope its not too difficult. Let me know.

**Comment by javulorg** [comment]
Do we have to do some settings for the SSL to create a valid connection?

      ![image](https://user-images.githubusercontent.com/19337355/54483887-7bd61f00-4829-11e9-8b86-714710c5bed9.png)

**Comment by acipher** [comment]
For SSL, I have followed the letsencrypt instructions but its not applying to http://javul.org. Though its working for https://www.javul.org/ (with www). I have checked solution but they are not working.

**Comment by javulorg** [comment]
I searched a bit on this topic for the search term "ssl not working without www" and found this link: https://really-simple-ssl.com/forums/topic/https-www-to-non-www-not-working/
Another: https://serverfault.com/questions/738883/ssl-certificate-non-www-not-working

The first site talks about a website that tests SSL: https://www.ssllabs.com/ssltest/analyze.html?d=javul.org&hideResults=on

Could it have something to do with how its setup for Linode servers?
Search results for this Google term:   [ssl site:linode.com](https://www.google.com/search?q=ssl+site%3Alinode.com&oq=ssl+site%3Alinode.com&aqs=chrome..69i57.159j0j9&sourceid=chrome&ie=UTF-8)

**Comment by acipher** [comment]
I tried with few more solution. It shows successful but not working see here https://i.imgur.com/blTzrIL.png

Can we get it checked by system admin? FYI: this can be done from http://javul.org:10000 webmin panel.

**Comment by javulorg** [comment]
I'm thinking Linode admins might not be able to help if its an issue with LetsEncrypt or a configuration issue, for example here's a comment on one thread on LetsEncrypt:  _As Linode is a VPS service, they have completely no responsibility regarding the support of software on their platform; that is the total responsibility of the user._

Here's Linode's documentation to help with LetsEncrypt: https://www.linode.com/docs/security/ssl/install-lets-encrypt-to-create-ssl-certificates/

When I do the SSL check: https://www.ssllabs.com/ssltest/analyze.html?d=javul.org&s=45.33.99.195&hideResults=on&ignoreMismatch=on
It says:   Alternative names:  INVALID

When I search "alternative names LetsEncrypt", there's this thread: https://community.letsencrypt.org/t/alternative-names-issue/51546

And this might be the most useful. Google search results for the query:
[not working without www site:letsencrypt.org](https://www.google.com/search?q=not+working+without+www+site%3Aletsencrypt.org&oq=not+working+without+www+site%3Aletsencrypt.org&aqs=chrome..69i57.111j0j9&sourceid=chrome&ie=UTF-8)
From the first link in this search, someone [says](https://community.letsencrypt.org/t/ssl-certificate-not-working-for-non-www-domain/62529/2): "you’ll need to issue a new cert covering both *.example.com and example.com."

I think there are good links for that 'www' search query. Hopefully one of those have a solution. For example in [this](https://community.letsencrypt.org/t/certificate-not-working-in-domain-without-www/53424) link the user's problem was resolved. In that link someone said _"Could you run certbot certificates please and post the output here?"_

What is good is that at least its working with www, as you mentioned, so thats good.

Posting a help note on the letsencrypt might be useful if these 'www' search query related forum links dont help: https://community.letsencrypt.org/

**Comment by javulorg** [comment]
SSL was fixed.
