### ISSUE TITLE
Global Links: Report a Concern

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#14]
“Report a Concern” link at bottom will go to an email form. Emailed to “javul.org AT gmail (dot) com”. Form will have an editable filled ‘Visited URL’ which will be pre-filled with the URL from which the ‘Report’ link was clicked. Form can be used even when not logged in and in that case to prevent spam, show anti-spam captcha.

**Comment by acipher** [comment]
Form will have an editable filled ‘Visited URL’ which will be pre-filled with the URL from which the ‘Report’ link was clicked.

->For example : user is on http://javul.org/issues page. and if user clicked on "REPORT A CONCERN" link. 
as you said "Email form" will contain "Visited URL" which is http://javul.org/issues in these case.

**do we need to show all data as shown in http://javul.org/issues?** 
or can  you please explain what are the other contains need to show in email form popup except visited URL?

![report_concern](https://cloud.githubusercontent.com/assets/3071346/22193656/d610bfb4-e162-11e6-8b05-b25efd33af38.png)

**Comment by javulorg** [comment]
That looks good. These are my suggested changes:
1. Create new text field "Visited URL". It will have the visited URL
2. The existing "Message" textbox will be empty.
3. Hide the Name and Email fields (so they are not visible to the user but still function in the form). For example by using this in the text field: input type="hidden"
4. Add one line of text below "Report a Concern". The line is: "Your message will be sent to the Javul.org administrator"

After the form is submitted, you can show a popup "Thank you! Your message was sent to the Javul.org admin".

I assume the text Captcha will not be there for logged-in users.

**Comment by acipher** [comment]
Enabled "Report a Concern"  link. Can you please check it and let me know if need to change.

**Comment by javulorg** [comment]
The information to show in the email:
     Subject of email:   Webform: Report a concern
Subject will not be shown in the email itself. It will be the subject of the email (like a regular email subject)

In the email itself:
---------
Visited URL: http:\\javul.org\unitABC\ ....

Message: Xyz

Submitted by: Username ABC

    Username ABC will be this when not logged in: Anonymous (not logged in)

Submitted through "Report a concern" webform.   <-- Please put this line in italics
----------

After you make the above changes, you could send a test message. I tested the form but I didnt get an email at javul.org AT gmail.com.

**Comment by acipher** [comment]
Made the said changes. and sent one mail to javul.org AT gmail.com. 

Can you please check?

**Comment by javulorg** [comment]
I received the email so it works, thanks. Could you remove the Social header at the bottom of the email? Its nice but I dont predict having Social links at this time (maybe in the future).

![image](https://cloud.githubusercontent.com/assets/19337355/23192400/2e245d58-f871-11e6-83d0-1c80f609d784.png)

**Comment by acipher** [comment]
I have removed social link portion. right now we are using our SMTP details that's why it's showing other email address. i will change from email address to javul.org AT gmail dot com once we configure SMTP of server.

**Comment by javulorg** [comment]
Thank you! Closed.
