### ISSUE TITLE
When user try to add fund for second time, 'Amount' field and 'Paypal Checkout' button is disabled.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#140]
Environment :- Windows 7, Mozilla Firefox Browser
Module :- Add Funds - Paypal
Credentials :- [johnCarter@mailinator.com](mailto:johnCarter@mailinator.com)
Priority :- Normal

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Objectives and select any objective.
3.Click on Add(+) icon of Funds.
4.Enter valid amount and click on Paypal.
5.Click back and observe.

Actual Result :- When user try to add fund for second time, 'Amount' field and 'Paypal Checkout' button is disabled.
Expected Result :- When user try to add fund for second time, 'Amount' field and 'Paypal Checkout' button should not be disabled.

Defect Video URL :- https://drive.google.com/file/d/1w8-o0X-ljQ4q5ie_FmGBIlAxtRofHa1e/view?usp=sharing

**Comment by acipher** [comment]
It should be fixed on #130.
