### ISSUE TITLE
"404 Page not found" an error message is displaying when user click on reply.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#141]
Environment :- Windows 7
Module: Chat
Credentials :- [john_k@mailinator.com]/11111111
Priority :Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on inbox
3.Now click on inbox message
4 click on replay
5 Observe

Actual result:  "404 Page not found" an error message is displaying when user click on reply.
Expected result: When user click on reply, error message should not be display.

 Video URL: https://drive.google.com/file/d/1WWpdGZAJhfr8i5z9H74P-VkfQr-68zm2/view?usp=sharing

**Comment by acipher** [comment]
Done please check and review.
