### ISSUE TITLE
 "Message send successfully"  confirmation message is displayed instead of displaying "message sent  successfully".

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#142]
Environment :- Windows 7
Module: Chat
Credentials :- [john_k@mailinator.com]/11111111
Priority :Normal

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on units
3.Click on Existing unit
 4 click on chat
4 click on replay
5 Send mail to existing user
5 Observe 

Actual result: "Message send successfully"  confirmation message is displayed instead of displaying "message sent  successfully".
Expected result: "Message sent  successfully" message should be displayed.

Video URL: https://drive.google.com/file/d/10V3qf98M1sbTFTLXrD2ofeUYV5sI0DpY/view?usp=sharing

**Comment by acipher** [comment]
Message changed please check and review.
