### ISSUE TITLE
Specific Unit displays Error message when clicked

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#143]
I saw this when not logged in:
1. Click on:  http://javul.org/units
2. Click on the 3rd unit called "software development" (where description is 'Welcome from John'). The direct link to that Unit is: http://javul.org/units/0Dpgbrgd6Q/software_development

It doesn't display the Unit information as for other Units and shows an error message.

**Comment by acipher** [comment]
Fixed now link is working.
