### ISSUE TITLE
While updating the task, Invalid validation messages and Error messages are displayed.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#144]
Environment :- Windows 7, Chrome Browser
Module :- Tasks
Credentials :- r6.pulsefbi@gmail.com
Priority :- Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Tasks and click on Add Task.
3.Enter valid data in all the fields and click on Create Task.
4.Click on Edit icon and change the status to 'Open for bidding'.
5.Click on Update Task and observe.
(All the mandatory fields are already filled with valid data, but still "this field is required" validation/error message is displayed. 'From Date' and 'To Date' fields are not displayed properly.)

Actual Result :- While updating the task, Invalid validation messages and Error messages are displayed.
Expected Result :- While updating the task, Invalid validation messages and Error messages should not be displayed.

Defect Video URL :- https://drive.google.com/file/d/1UnuhrixF9Rn78oZngv02GBwhiCn7WwPV/view?usp=sharing

**Comment by acipher** [comment]
Fixed @javulorg and @Shivakumarbv can you please check and confirm.

**Comment by javulorg** [comment]
Thanks, closing this.
