### ISSUE TITLE
All the mandatory fields is not highlighted when user tries to create issue

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#145]
Environment :- Windows 7
Module: Create issue
Credentials :- [[john_k@mailinator.com]/11111111
Priority :Major

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2 Click on issues and click on add issue
3 It will navigate to create issue page
4 Click on create issue without entering any fields
5 Observe

Actual result: All the mandatory fields is not highlighted when user tries to create issue
Expected result: All the mandatory fields should be highlighted when user tries to create issue.

Video URL : https://drive.google.com/file/d/1NzW4i3X99N5IGN7B5sbX3Agb9Rux7rDQ/view?usp=sharing

**Comment by acipher** [comment]
All required fields to be highlighted.
![image](https://user-images.githubusercontent.com/3071346/54009293-40d04d80-4190-11e9-94b0-f081c312c0bb.png)
