### ISSUE TITLE
'No Featured Unit' is already displayed, but still 'No Description Available' is displayed unnecessarily.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#146]
Environment :- Windows 7, Chrome Browser
Module :- Home page
Credentials :- [r6.pulsefbi@gmail.com](mailto:r6.pulsefbi@gmail.com)
Priority :- Normal

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Navigate to Home page and observe.

Actual Result :- 'No Featured Unit' is already displayed, but still 'No Description Available' is displayed unnecessarily.
Expected Result :- When 'No Featured Unit' is already displayed, Then 'No Description Available' should not be displayed unnecessarily.

Screenshot :- 
![javul - home page - 20190206-165548](https://user-images.githubusercontent.com/7206531/52391649-56385600-2ac4-11e9-863c-33b39fe5861b.png)

**Comment by acipher** [comment]
Should be fixed now. Please review.
