### ISSUE TITLE
Unnecessary Search field is displayed in 'Login Page' and 'Forgot Password' page.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#147]
Environment :- Windows 7, Chrome Browser
Module :- Home page
Priority :- Normal

Steps to reproduce :-
1.Open Javul Site.
2.Navigate to Login page and observe.
3.Navigate to Forgot Password page and observe.

Actual Result :- Unnecessary Search field is displayed in 'Login Page' and 'Forgot Password' page.
Expected Result :- Unnecessary Search field should not be displayed in 'Login Page' and 'Forgot Password' page.

Screenshot :-
![javul - search field - 20190206-171950](https://user-images.githubusercontent.com/7206531/52392227-e37caa00-2ac6-11e9-87c0-27fb5ca5770f.png)
![javul - search field - 20190206-171919](https://user-images.githubusercontent.com/7206531/52392228-e37caa00-2ac6-11e9-913a-5657302a77b0.png)

**Comment by javulorg** [comment]
If there is an easy way to remove the Search bar for these two pages, please do so, otherwise this ticket can be closed.

**Comment by acipher** [comment]
Should be fixed. Removed from login and forgotpassword pages. Please check
