### ISSUE TITLE
Previously sent message content in all the fields are still displayed even after sent email successfully.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#148]
Environment :- Windows 7
Module: Create issue
Credentials :- [[john_k@mailinator.com](mailto:john_k@mailinator.com)]/11111111
Priority :Normal

Steps to reproduce:-
1. Open Javul Site and log in with valid credentials.
2 Click on email
3. Click on new mail
4 Fill all the details and click on send the message
5 Observe 

Actual result: Previously sent message content in all the fields are still displayed even after sent email successfully.
Expected result:  Previously sent message content in all the fields are should not be displayed once message sent page should be refreshed.

Video URL: https://drive.google.com/file/d/1VsixJS3f1MJHtVvn6KJKxOOwB1uPUxSm/view?usp=sharing

**Comment by acipher** [comment]
Subject field was not getting cleared. Should be fixed now. Please review.
