### ISSUE TITLE
User-2 is receiving multiple invitations for the same task.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#149]
Environment :- Windows 7, Chrome Browser
Module :- Home page
Credentials :- User-1:- r6.pulsefbi@gmail.com / User-2:- johnCarter@mailinator.com
Priority :- Normal

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Tasks and click on Add Task.
3.Enter valid data in all the fields and click on Create Task.
4.Click on Edit icon of task and Change the status to 'Open for bidding'.
5.Update the task and logout.
6.Login as user-2 and Click on Tasks.
7.Click on Bid Now and enter valid data in all the fields and Bid.
8.Login as user-1 and Assign the task to user-2.
9.Login as user-2 and click on Tasks and observe.

Actual Result :- User-2 is receiving multiple invitations for the same task.
Expected Result :- User-2 should not receive multiple invitations for the same task.

Screenshot :-

![javul - task invitation - 20190207-120527](https://user-images.githubusercontent.com/7206531/52396042-4295eb00-2ad6-11e9-9fdb-1e95d4655ade.png)

**Comment by acipher** [comment]
its not multiple invitation. Fixed the issue. Please review.
