### ISSUE TITLE
Some pages require Login

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#15]
View of many items requires a login, e.g. Objectives,  Tasks,  Issues, Individual Issue,  Global Activity Log. Fix so these items can be viewed without a login.

**Comment by acipher** [comment]
Made the said change. Please review.

**Comment by javulorg** [comment]
If not logged in, view of an issue gives an error:
http://javul.org/issues/paQnKX1mMv/view

**Comment by acipher** [comment]
i have resolved "If not logged in error". can you please check it?

**Comment by javulorg** [comment]
Thank you, I closed this.
