### ISSUE TITLE
User not able to update task even status is displaying as editable.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#150]
Environment:- Windows 7
Module: Tasks
Credentials :- [[john_k@mailinator.com](mailto:john_k@mailinator.com)]/11111111
Priority :Major

Steps to reproduce:-
1. Open Javul Site and log in with valid credentials.
2. Click on tasks
3. Click on existing tasks
4. (For task automation testing 3- status is editable)
5. Click on edit
6. Observe in update task user not able to edit task.

Actual result: User not able to update task even status id displaying as editable.
Expected result: If the status is displaying as an editable user should able to edit the task.

VIdeo URL https://drive.google.com/file/d/1B_auIi-TVrue0dY-ch1OSVuU0XkUxZvZ/view?usp=sharing

**Comment by acipher** [comment]
@javulorg can you validate the issue? Is it correct? if yes I can enable the status change. Thanks

**Comment by javulorg** [comment]
Closing this, I was able to the task.
