### ISSUE TITLE
Without entering any data in any field, when user click on 'Cancel Task', validation/error message is not displayed.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#151]
Environment :- Windows 7, Chrome Browser
Module :- Tasks
Credentials :- User-1:- [r6.pulsefbi@gmail.com](mailto:r6.pulsefbi@gmail.com) / User-2:- [johnCarter@mailinator.com](mailto:johnCarter@mailinator.com)
Priority :- Normal

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Tasks and click on Add Task.
3.Enter valid data in all the fields and click on Create Task.
4.Click on Edit icon of task and Change the status to 'Open for bidding'.
5.Update the task and logout.
6.Login as user-2 and Click on Tasks.
7.Click on Bid Now and enter valid data in all the fields and Bid.
8.Login as user-1 and Assign the task to user-2.
9.Login as user-2 and click on My Tasks.
10.Click on Cancel Task.
11.Without entering anything click on Cancel Task button and observe.

Actual Result :- Without entering any data in any field, when user click on 'Cancel Task', validation/error message is not displayed and also user is unable to cancel the task.
Expected Result :- Without entering any data in any field, when user click on 'Cancel Task', validation/error message should be displayed.

Defect Video URL :- https://drive.google.com/file/d/1c-6aw_2kxU46ZvikvOCxwxSRfU5SH_rK/view?usp=sharing

**Comment by acipher** [comment]
Provided appropriate validation message. Please check attachment.

[https://drive.google.com/file/d/1KmKSjv8_snvBsK2KPOJB6d74piFj1RkQ/view?usp=sharing](https://drive.google.com/file/d/1KmKSjv8_snvBsK2KPOJB6d74piFj1RkQ/view?usp=sharing)
