### ISSUE TITLE
For 'Cancel Task' page, 'Complete Task' title is displayed.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#155]
Environment :- Windows 7, Chrome Browser
Module :- Tasks
Credentials :- User-1:- [r6.pulsefbi@gmail.com](mailto:r6.pulsefbi@gmail.com) / User-2:- [johnCarter@mailinator.com](mailto:johnCarter@mailinator.com)
Priority :- Normal

Steps to reproduce :-
1.Open Javul Site and login with valid credentials.
2.Click on Tasks and click on Add Task.
3.Enter valid data in all the fields and click on Create Task.
4.Click on Edit icon of task and Change the status to 'Open for bidding'.
5.Update the task and logout.
6.Login as user-2 and Click on Tasks.
7.Click on Bid Now and enter valid data in all the fields and Bid.
8.Login as user-1 and Assign the task to user-2.
9.Login as user-2 and click on My Tasks.
10.Click on Cancel Task and observe.

Actual Result :- For 'Cancel Task' page, 'Complete Task' title is displayed.
Expected Result :- For 'Cancel Task' page, 'Cancel Task' title should be displayed.

Screenshot :- 
![javul - cancel task - 20190207-152100](https://user-images.githubusercontent.com/7206531/52407423-4174b600-2af6-11e9-91f2-d0198e2f673c.png)

**Comment by acipher** [comment]
Should be fixed now. Please review.
