### ISSUE TITLE
User Account: Required fields

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#19]
For User profile/account, only the username and password are required fields. All other fields are optional such as email, mobile, phone, first name, last name, location.  All these fields can be left empty.

**Comment by acipher** [comment]
I think it will be closed after you check point #27

**Comment by javulorg** [comment]
Thanks, closed.

**Comment by javulorg** [comment]
Igor, this is a new issue for you. It seems like the previous team did not implement this.
During User registration: http://javul.org/register
Only the username and password are required fields. All other fields are optional such as email, mobile, phone, first name, last name, location. All these fields can be left empty.

**Comment by javulorg** [comment]
Just make sure its only email, username and password that are required (first and last name are not required). If its already like this you can close this.
