### ISSUE TITLE
Activity points: Calculation and Display

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#20]
Activity Points: How are they calculated and shown on user profile? Do we need dedicated fields for retrieval? We can duplicate data storage thats ok. So in ‘users’ table, we can create new DB field called ‘activity_points’ and update when the number has to be updated. This will be helpful later also (e.g. showing users with most activity points).

**Comment by acipher** [comment]
Added "activity_points" field into users table also updated when record inserted into activity points table.

Please review.

**Comment by javulorg** [comment]
Thanks, closed.
