### ISSUE TITLE
(do at end) DB and Github Cleanup

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#21]
At the end of the project, remove unused tables and fields from DB (makeup backup first). This can be done after FWC integration is completed.

Also remove any extra unused files on Github and remove extra Github FWC branch:

![image](https://cloud.githubusercontent.com/assets/19337355/23344064/d7f03566-fc43-11e6-9a71-e684802adf4a.png)

![image](https://cloud.githubusercontent.com/assets/19337355/23344068/e59cc850-fc43-11e6-9527-34687731210a.png)

**Comment by acipher** [comment]
I have removed unused tables.

To delete unused branch please follow steps included in below link.
https://help.github.com/articles/deleting-and-restoring-branches-in-a-pull-request/

**Comment by javulorg** [comment]
Thanks, I deleted the two branches. I made a backup before doing it. 
I dont know how to delete this folder:
![image](https://cloud.githubusercontent.com/assets/19337355/24653005/054cd2e6-1902-11e7-8003-3450c868a5c4.png)

https://github.com/javulorg/javul

**Comment by acipher** [comment]
FWC folder removed.

**Comment by javulorg** [comment]
Thanks! Closing this issue. All issues are now resolved. I'll send the last payments tonight with the bonus.
