### ISSUE TITLE
Global Site Search

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#24]
Search box at top will search the titles of Units, Tasks, Objectives, Issues for those keywords. Divide Search results by Object type (Units, O/T/Issues). Option to also do full search that includes item description.

**Comment by acipher** [comment]
Enabled "Global search". can you please check it and let me know if you need anything to change.

**Comment by javulorg** [comment]
Thanks the search is working. Could you add a page header to show its the search page? For example "Search Results"
http://javul.org/global_search

The header can look like the Unit page header:
http://javul.org/units/0Dpgbrgd6Q/test_unit_2
The icon used can be the typical search icon: http://fontawesome.io/icon/search/
Instead of green, the color can be some kind of Dark Gray. The text "Search Results" will appear in place of "Unit Information"


Also is it possible to put the search term in the URL so it can be linked? Currently when I copy page the search link it gives an error:
http://javul.org/global_search

I would like so this URL works and shows the results of that term:
http://javul.org/global_search&search_term=Test
You can have the URL in any form as long as it contains the search term. I believe some characters have to be escaped in URL's for example %20 for space and so on.

If thats hard to do, you can just make it so when I click on that link the page says "No search term was specified". I can have this feature fixed sometime later.

**Comment by acipher** [comment]
Made the said change. Can you please check it? 

Please let me know if need to change.

**Comment by javulorg** [comment]
Thank you. Everything looks fine except for the header. Could you add a separate section so we have a section for "Units" just like we have for Objectives and Issues?
http://javul.org/global_search?search_term=human+rights

So the section in blue moves down and a new table section header "Units" will be created:
![image](https://cloud.githubusercontent.com/assets/19337355/23239097/3303891c-f933-11e6-88f4-b05dbd588d60.png)

This way we know the items listed are Units.

**Comment by acipher** [comment]
Created new section for Unit. Can you please check again?

Please let me know if need to change.

**Comment by javulorg** [comment]
Looks good. Could you make the vertical space the same as the bottom two ones? The top two spaces should be the same as the space at location "1"
![image](https://cloud.githubusercontent.com/assets/19337355/23287432/5d6117dc-fa0b-11e6-8269-1199fdd6b8f8.png)

**Comment by acipher** [comment]
Made the said change. Please review.

**Comment by javulorg** [comment]
Thanks, closed.
