### ISSUE TITLE
Task Management: Site Template fix

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#25]
‘Task Completion’ Top buttons need to be updated to match rest of website (login as admin@javul.org /123456 and view this link: http://javul.org/tasks/complete_task/Zdb24k9kjW)
On this same page the small table ‘Task Information’ can be deleted.

**Comment by acipher** [comment]
Added space to top buttons and removed Task information table. Please review.

**Comment by javulorg** [comment]
It works but I feel this page should follow the same template as that of the Unit, for which the task belongs to. Could you change the template for this page, so we see a view like that of a Task page?
http://javul.org/tasks/MNZ8Gq2ekj/test_task_8
So we'll see the Unit information table on the left and the unit activity log etc.

You can use the same icon color as that for a task (yellow).
As for the header of the new page, you can use "TASK MANAGEMENT: Complete Task"

![image](https://cloud.githubusercontent.com/assets/19337355/21958748/221a398a-da83-11e6-9eb9-728f49d1b6f4.png)

**Comment by acipher** [comment]
Can you please check this http://javul.org/tasks/complete_task/Zdb24k9kjW?

**Comment by javulorg** [comment]
For this view, the task skills are not showing up:
http://javul.org/tasks/complete_task/Zdb24k9kjW
Compare to: 
http://javul.org/tasks/Zdb24k9kjW/task_management

If this is fixed I will close it.

**Comment by acipher** [comment]
Made the said change. can you please check? i have shown skills in http://javul.org/tasks/complete_task/Zdb24k9kjW

**Comment by javulorg** [comment]
Thanks, closed.
