### ISSUE TITLE
Task Management: Create way to create and display Task Feedback

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#26]
When a task is completed, it can be rated for two types of feedback: Quality of work  (rating Stars from 1 to 5 and allow to rate for 0.5 stars increments), Timeliness (1 to 5 with 0.5 increments). 
If user X completes 10 tasks, then the average rating is calculated and shown on the user’s profile and when they are placing a bid.” For example, 
Task Completion Ratings: Quality of Work: **** (4.5/5)  Timeliness: *** (3.0/5)

Suggestion: The two categories should be created within user tables, since they are related to how a specific user completed a certain task. Let me know and we can discuss the Database structure.
We want to store individual task rating information and also the average ratings.

**Comment by acipher** [comment]
**We want to store individual task rating information and also the average ratings.**

Suggestion: we are storing bidder information in task_bidder table. we can take these two fields into task_bidder table. we have user information to whom task assigned and that task completed.

please confirm.

**Comment by javulorg** [comment]
To me the task_bidder table's name shows it only contains bidding information about tasks. When we are bidding on a task there are no ratings yet. So either we should change the name of the table to make it more general (e.g. task_management) or store the Task ratings in a new table. I see there are many Task related tables in the Db so I guess a new one could be created called "task_ratings".
As for the average rating, that rating belongs to a user. I think it will be good to have that rating in the User table because when we are fetching User data, we can get it all in the same table so its a faster DB query. But its up to you where you want to store it.
Just make sure the table name is related to the columns it has. This way its easier to understand for anyone who works on the project in the future.

**Comment by javulorg** [comment]
On second thought, your solution is fine. You can store the information in the task_bidder (or any other table).

**Comment by acipher** [comment]
![ss](https://cloud.githubusercontent.com/assets/3071346/23154707/4249969a-f835-11e6-9e39-859b95aa0ce2.png)

Can you please check attached screenshot?

for user profile of : http://javul.org/userprofiles/mnDZmKNaWw/matt_prior

quality of works average points : 2.75
timeliness average points : 5.75

Please suggest where to show and where star below profile picture will update?

**Comment by javulorg** [comment]
I thought about it. You can display the data field "quality of works average points" in the Stars view and show it like this:
Task Completion Rating
(stars) 2.8 / 5

So for any value, you can round to one decimal place and show that value as above. So 2.75 becomes 2.8
For the visual display of stars, we have to decide how many stars to show. For that you can use your best judgement and it will be fine. 
My suggestion: We can show stars with any values of these: 0.5, 1, 1.5, ...up to  5. This is similar to most other websites. You can use comparison to decide if 2.8 is closer to 2.5 or 3 and then show accordingly. 

As for "Timeliness" we can just leave that data in the database for now. So it will be rated and calculated but not shown anywhere at this time. I might decide on it in the future (after this project is complete) as to where to show it.

**Comment by acipher** [comment]
I have shown average points of only "quality of works" below the profile picture, based on that i have shown star also.
- rounded value ex. if 2.75 then it will be 2.8

you can check  here : http://javul.org/userprofiles/mnDZmKNaWw/matt_prior

I have used star rating plugin : http://plugins.krajee.com/star-rating/demo

Please review. let me know if need to change.

**Comment by javulorg** [comment]
Looks good. Thanks, closed.
