### ISSUE TITLE
User Account: Timezone setting

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#27]
Let user select their Timezone in the Account settings.

**Comment by acipher** [comment]
Added field timezone in user profile. Please review.

**Comment by usmaans** [comment]
I'm not able to change the timezone and save it. I checked both in Firefox and Chrome.

**Comment by javulorg** [comment]
I'm not able to update the time zone using both Firefox and Chrome. Also could you make it so 
(1) time zone is set to the first entry as default when account is created. This might already work. 
(2) The only required fields in the User account are First name, last name and email?

**Comment by acipher** [comment]
I'm not able to update the time zone using both Firefox and Chrome. Also could you make it so
![timezone_ff](https://cloud.githubusercontent.com/assets/3071346/22009585/33237df8-dcaa-11e6-9f13-ca4db5b0b46b.png) this is firefox screenshot 
![timezone_chrome](https://cloud.githubusercontent.com/assets/3071346/22009605/59e2c480-dcaa-11e6-9952-e0a94e8dd109.png) this is chrome sceenshot. i have tested on both.

2)The only required fields in the User account are First name, last name and email? - i will change this.

but can you please explain more for point 1?
When any user register into system do we need to take timezone and store into db?

**Comment by javulorg** [comment]
For this view, when I try to change the mobile number it says "Invalid mobile number", so I couldn't save the form and test it. If I enter any number it doesn't let me save. If its empty, it lets me save.
For the mobile number check, only test to make sure there are no alphabetic characters in the field. It can also be left empty.

For timezone, if I try to change it, and then save it, the 'save' button does not click and I cannot save the data.

>  When any user register into system do we need to take timezone and store into db?

Yes please create a 'timezone' field in the user table. The field above when changed in the Profile settings, will be stored in the db. When the user visits their account profile, the field will be restored from the DB. This field will be used later.

**Comment by javulorg** [comment]
I see this existing issue related to the required fields: https://github.com/javulorg/javul/issues/19
I will close that after its resolved.

**Comment by acipher** [comment]
For this view, when I try to change the mobile number it says "Invalid mobile number", so I couldn't save the form and test it. If I enter any number it doesn't let me save. If its empty, it lets me save.

FYI: we have used country wise mobile number testing library. link is "https://github.com/giggsey/libphonenumber-for-php"

**do we need to remove these mobile number library testing? and only test to make sure there are no alphabetic characters in the field. It can also be left empty.** as you said.

**Comment by javulorg** [comment]
Sure you can disable the number testing library but keep it in the system so it can be re-enabled later if needed. Yes just test to make sure there are no alphabetical characters (a-z,A-Z).
I see the timezone is now saving correctly, Thanks for that. So I will close this ticket after the phone number testing is removed.

**Comment by acipher** [comment]
Disabled "Mobile number checking". Can you please check again?
