### ISSUE TITLE
Date Hover

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#28]
Time-elaped is displayed often on the site in multiple places, e.g. "2 hours ago". Anywhere we mention the time elapsed, I would like to see the actual timestamp when the mouse is on hover. Show timestamp according to user’s timezone.

**Comment by acipher** [comment]
Shown timestamp according to user's timezone if user has set timezone field in account setting area else it will shown server's timezone.

Please review. let me know if need to change.

**Comment by javulorg** [comment]
Thanks, its showing now in most places except for the Global activity log: 
http://javul.org/activities

**Comment by acipher** [comment]
Added to mentioned page also. Please review.

**Comment by javulorg** [comment]
Thanks, closed.
