### ISSUE TITLE
Text Edits: Insert Hyperlinks

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#29]
Text edit functions: In addition to the existing bold/italic buttons, we need to add button for “Insert Hyperlink”. This applies to all text edits for all objects.

**Comment by acipher** [comment]
Can you please explain in detail? and where to change this?

**Comment by usr54391** [comment]
I'm referring to the toolbar that appears when we're editing any object e.g. when editing an Objective or Issue etc:

![image](https://cloud.githubusercontent.com/assets/25126384/22003434/82dc2e50-dc21-11e6-9c24-29c1890fdca4.png)

The toolbar could have an "Insert link" button. Maybe this specific toolbar already has a built-in Hyperlink functionality?

**Comment by javulorg** [comment]
I'm referring to the toolbar that appears when we're editing any object e.g. when editing an Objective or Issue etc:

![image](https://cloud.githubusercontent.com/assets/25126384/22003434/82dc2e50-dc21-11e6-9c24-29c1890fdca4.png)

The toolbar could have an "Insert link" button. Maybe this specific toolbar already has a built-in Hyperlink functionality?

**Comment by acipher** [comment]
Added link option. FYI: last option is "Insert Link". can you please check and let me know if you need to change anything.

**Comment by javulorg** [comment]
Thanks, it works now.
