### ISSUE TITLE
[reopen later] Site Activity Logs-additional items

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#3]
- “New account” should add entry to the Activity logs: “User X created an account” 
- Show “in Unit X” in Global activity logs. When the same log items are viewed in a Unit, we dont need to show "in Unix X". This can be easy to do if the other issue is resolved: https://github.com/javulorg/javul/issues/2
- On the log page, allow these actions (provide search abilities):
-- Display all actions of a certain user (enter username or search for it)
-- Display all actions of a certain kind (e.g. list all Donations, All Task edits, Task completions etc)
-- All actions done on a certain object (object can be a unit, objective, task, issue)

**Comment by acipher** [comment]
On the log page, allow these actions (provide search abilities):
-- Display all actions of a certain user (enter username or search for it)
-- Display all actions of a certain kind (e.g. list all Donations, All Task edits, Task completions etc)
-- All actions done on a certain object (object can be a unit, objective, task, issue)

- we have to provide only single searchbox for all types? or can you please explain more or can you please provide UI for these search?

**Comment by javulorg** [comment]
> we have to provide only single searchbox for all types search? or can you please provide UI for these search?

Most likely we need separate boxes. The goal is to be able to do these kinds of DB queries:
- Select * from activity table, where user=ABC
- Select * from activity table, where action-type=ABC

I would have to do some investigation on the activity types and how to display them and the UI specifications. For now we can postpone this issue. I can remove the assignment from your username. I will take a look at this again sometime in the future (after this project so you dont have to do it).

**Comment by javulorg** [comment]
I'll reopen this later.
