### ISSUE TITLE
(Optional) Guide for working on the Site

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#30]
Create a very short Guide Document for anyone on how to edit the site. (Learn Laravel, Github etc). Steps for changing something on the site for future developers.

**Comment by acipher** [comment]
[User-Guide.docx](https://github.com/javulorg/javul/files/890250/User-Guide.docx)

Please find attached User Guide doc of Javul.org.

**Comment by javulorg** [comment]
Thanks for making that doc. So I assume the instructions near the end are enough to tell anyone how to make any changes to the site.

**Comment by acipher** [comment]
Doc is just user manual explaining the site and its functionality. Making doc how to edit is not possible as it will be huge.  Site is made with laravel coding standards. It will be easy for anyone to make edit if they know the laravel with logical/technical experience.

**Comment by javulorg** [comment]
Thanks! Closing this.
