### ISSUE TITLE
Some Page views need to be updated

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#32]
1. When an Objective is edited, the view should show everything else seen on other Unit related pages. Unit table information on left and so on.
To reproduce, go to: http://javul.org/objectives/jBgOX93Ppm/hgfhfg
Then click the "Edit" icon
Also make sure that after the edit is done, the user is returned to the object edited. Currently it goes to the list of objectives.

![image](https://cloud.githubusercontent.com/assets/19337355/22576855/3151e174-e98c-11e6-985a-11b103b8db22.png)

2. The same issue is present for any Tasks page. The view should show all the other information and after updating, it should go to the Tasks page.
http://javul.org/tasks/MNZ8Gq2ekj/test_task_8

3. This page is missing the page footer at the bottom: http://javul.org/site_admin (Links for report a concern, etc)

Could you check if the FWC code overwrote some of the fixes done previously? I hope this is easy to check and to take care of. I feel some issues are old and were fixed but I cant remember for sure. In any case if you could check, that would be great.

**Comment by acipher** [comment]
It should be fixed now and also checked the redirection after update of unit/obj/task/issue.

Can you please?

**Comment by javulorg** [comment]
Thank you! Closed.
