### ISSUE TITLE
Task page does not show Summary field

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#33]
The task page does not show the "Summary" data field.

To reproduce, edit any task, change the Summary field and see if it displays on the Task page:
http://javul.org/tasks/MNZ8Gq2ekj/test_task_8

**Comment by acipher** [comment]
Shown "Summary" field on the page. 

Can you please check?

**Comment by javulorg** [comment]
Thanks its showing now. I noticed two things:
(1) When we edit a task, the page header shows "Create task". 
![image](https://cloud.githubusercontent.com/assets/19337355/23192135/afcacd9e-f86f-11e6-8b94-88f3675527fb.png)
It should say 'Update Task".
I checked and edits for Unit and Issue are ok.
http://javul.org/tasks/MNZ8Gq2ekj/test_task_8

(2) On the Task page, could you change the order of Sections for both "view of Task" and "edit of task" as follows:
General Task Info (start, end date etc), Summary, Description, Action Items, Documents, Comment.
Currently the order is different.

On Task View page, please remove the section showing Objective information. Just the name of the Objective is enough:
http://javul.org/tasks/7mX80l8wJ3/gdfgfd
![image](https://cloud.githubusercontent.com/assets/19337355/23192240/61f030f4-f870-11e6-91f3-aaad0d03e637.png)

I will then close this issue. Thanks.

**Comment by acipher** [comment]
1) When we edit a task, the page header shows "Create task". : ** Changed text to Update Task **
2) Changed the order of fields on edit task and view task page. 
3) Removed objective description from view task page

Can you please check? Please let me know if need to change.

**Comment by javulorg** [comment]
Thanks! Closed.
