### ISSUE TITLE
Error when saving an Issue

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#34]
There is an error when saving an Issue. e.g.
http://javul.org/issues/paQnKX1mMv/edit
Edit and then try to save the page.

**Comment by acipher** [comment]
It should be fixed now. can you please check?

**Comment by javulorg** [comment]
It saves but now after it saves, it goes to the Issue list, instead of the Issue page. For example if I edited "Issue 123", after the edit, it should show me the page for "Issue 123" instead of showing the list of issues.
I think these things were fixed before. Somehow the code got overwritten possibly during the FWC changes.

**Comment by acipher** [comment]
Ohh. i will check with unit, objective, task after it should go to view page. right now i have changed code to redirect issue view page. can you please check again?

**Comment by javulorg** [comment]
Thanks, fixed and closed.
