### ISSUE TITLE
Check Notification Email for Objects

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#36]
Edit of a Unit sends an email notification that needs to be fixed. Check other email notifications too.

Also check the format of a notification email. For example we want the notifications to come from the address "notifications AT javul.org"

The "reply to" address for that email should be: "no-reply AT javul.org"
So when user clicks reply to the notif email, thats what should appear in the "to" field.

**Comment by Motordread** [comment]
As I can see notifications for unit edit works fine. Please check it again and let me know steps to reproduce if you find bug.

**Comment by Motordread** [comment]
I've turned on sendmail on the server, so now we can receive real emails.

**Comment by javulorg** [comment]
hi Igor,
I did some testing. Yes the email comes now but there are a lot of issues that need to be fixed. Should these be moved to the next contract? Let me know. I have tried to create some order in this list.

1. On the Wiki, please make a page and create a list of all possible notification emails so we can keep track of them. Call the page "Notification Emails"

2. Notif emails are getting caught in Gmail's spam filter. To test, make a user with a Gmail email address and test the notifs there. Gmail says "Why is this message in Spam? It is in violation of Google's recommended email sender guidelines.  Learn more". It goes to this link: https://support.google.com/mail/answer/81126?hl=en#authentication

3. Most likely we want to have a universal template for sending Notif emails and then use that template for sending all Notif emails on site. It will make sending the Notif emails easier and make it easy to make changes to all Notif emails. Template can have these variables: Subject, User-ID, Main Content, Notification-Reason.  Inside the template, User-ID will be used to get other parameters such as: (a) Target email address. (b) Username (c) Link for "Manage Email Notifications".  Add other variables if needed. 

Once the template is created, we want it to have the following features:
 * 3.1 Notif emails need to get rid of Grey box at bottom with Twitter, etc. Also get rid of the big Orange bar at top. Keep the logo but use it tastefully with your own judgement as to how the Notif email should look like. You can look at any sample emails from other companies in your inbox and get ideas from there.
 * 3.2 Inside email "Manage Alert Setting" link goes to 404.  We want it to go directly to a view that allows user to change their Alert settings. Also change text of this link to "Manage Notification Settings"
 * 3.3 Notif email is addressed wrongly. It says "hi [name of user who did the activity]", instead of "hi [User who has the item on the watch list]".
 * 3.4 Add note at bottom of all Notif emails: "You are receiving this email notification because [you added an item to your watchlist]"    --   [] = whatever action was done to enable that alert.  This will become the "Notification-Reason" variable for the template.

4. Notification should not be generated for this activity: User ABC creates an objective or Task and they themselves get an email. Turn off this email.

5. Do site-wide search for this email (aadhyatechnologies34 at gmail..) and replace it with "notifications@javul.org". I got two emails with the 'aad...' emails address for the above activities (Task Created, Objective Created) mentioned in item 3.

6. Are notifs emails generated twice for Objective and Task edits? I got them two times. Please check. We need only once.

All the above applies to all notif emails (Objective, Task, check any others)

**Comment by javulorg** [comment]
We need to combine both Notif related issues into one. The other one is #4 
I will try to do it this weekend.

I think what we should do is move stuff to the Wiki where we can all work on the specifications of a complex issue together.
So, I will work on the wiki page for Notif specifications this weekend. It may not be complete but it will be a start. We need to check all the stuff on both these issues to make sure any missing functionalities are implemented/fixed
