### ISSUE TITLE
Category link leads to error page

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#39]
Steps to Reproduce:
1. Open th test url: http://www.javul.org/
2. Complete sign up process.
3. Click on 'Unit' tab.
4. Click on any unit category displayed in the list and verify.

Actual result:
Clicking on the category name leads to '404 page not found' error

Expected result:
Appropriate page should be displayed instead of error page.

Screenshot: https://www.screencast.com/t/hbhdz83he

**Comment by Motordread** [comment]
What page user should see if he clicks on that category?
http://prntscr.com/fizn98

**Comment by javulorg** [comment]
I thought about it. Its possible that the expected page view doesn't exist so it has to be created.
A link to a category should display all units that use that category. The page title can be something like
"Unit Category Listing"
Showing all Units with category "ABC"

Unit Name and Link         |     Unit Location
Test123                            |    Location 1

This same kind of category link is also displayed for a Unit home page too:
![image](https://user-images.githubusercontent.com/19337355/27053890-fe7dd016-4f8c-11e7-9892-05887cb05aea.png)

I checked and I think there's no issue opened for the above but they are both similar.

**Comment by javulorg** [comment]
I forgot to include the sample DB query. It would be something like: Select unit_name, unit_location from units_table where category_name=ABC

Ed

**Comment by javulorg** [comment]
hi Igor,
So here's the desired behavior. For example if the category of a Unit is Software, the link on that text (highlighted above) will be something like:    http://javul.org/units/category=software   (currently this link is not working)
When I click on that link, it will open up this Units search page with that selected category and display all units that have that category. The closest existing page I see is this:   http://javul.org/units
Thats the main Units link at the top of all pages. It already has a Category search function. We just want the functionality that when someone visits a URL like this, the search field will be populated automatically with 'Software' and the results will be displayed.
Let me know if you need more info.
Ed
