### ISSUE TITLE
Multiple error messages displayed for clicking on Add to watch list.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#40]
Steps to Reproduce:

1. Open the test url: 
http://www.javul.org/
2. Login with valid credentials
3. Click on 'Unit' tab and create the Unit
4. Click on recently created unit
5. Click on multiple times 
 'Add to watchlist or + icon' and observe.

Actual result:
"Clicking on multiple times on  'Add to 
watchlist' displays multiple error messages."

Expected result:
"Clicking on multiple times on  'Add to 
watchlist' should displays single error messages."

Screenshot:  https://www.dropbox.com/s/1tuxfz687fwpt3g/error%20message.png?dl=0

**Comment by Motordread** [comment]
Fixed
