### ISSUE TITLE
Clicking on Private Message button leads to '404 Page not found error; page.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#45]
Steps to Reproduce:

1.  Open the test url: http://www.javul.org/
2. Login with valid credentials.
3. Click on created unit
4. Click on Chats.
5. Click on the name displayed.
6. Click on Private message button and verify.

Actual result:
Clicking on Private Message button leads to '404 Page not found error; page.

Expected result:
Appropriate page should be displayed instead of error page.

Screenshot: https://www.screencast.com/t/pMkjklqk5kQl

**Comment by Motordread** [comment]
http://prntscr.com/fjm9of
It works this way: if user write message to himself he will get 404 page. Please let me know what should we do in this case.

**Comment by javulorg** [comment]
If we are clicking on our own username, the popup that appears should just contain the link "My Profile" and then link to the profile of the logged in user.
Something like:  http://www.javul.org/userprofiles/e0WZaAZD2P/javul_admin

**Comment by Motordread** [comment]
No problem, it's done.
