### ISSUE TITLE
"User search" is not functioning.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#46]
Steps to Reproduce:

1.  Open the test url: http://www.javul.org/
2. Login with valid credentials.
3. Click on created unit
4. Click on chat 
5. Enter any name in ""User Search "" 
and observe.

Actual result:
"User search" is not functioning.

Expected result:
Respective search result should display in User search.

**Comment by Motordread** [comment]
Can't replicate it, it works for me, from 2nd symbol script start searching. Please recheck this bug.

**Comment by javulorg** [comment]
It works for me also. Shiva, could you kindly recheck?

Igor,
We could add some kind of visual distinction to let the user know that the list below is now filtered by the Search results. This will show the user the search is active. Its up to you how you want to handle it or you can leave it as it is (up to you).

**Comment by javulorg** [comment]
Igor, you can resolve this issue as you like (see my comments above).
