### ISSUE TITLE
Notification list become empty after clicking on "See All"

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#51]
Steps to Reproduce:

1.  Open the test url: http://www.javul.org/
2. Login with valid credentials.
3. Click on Notifications
4. Click on ""See all"" and observe.

Actual result:
Notification list become empty after clicking on "See All"

Expected result:
Notification list should be display after clicking on "See all".

**Comment by Motordread** [comment]
Can't replicate - http://prntscr.com/fjnk4k I see notifications after clicking see all.

**Comment by Shivakumarbv** [comment]
Working as expected.
Screencast: https://www.screencast.com/t/inb24bNXu8B
