### ISSUE TITLE
(solve with #66) Clicking on "pay pal checkout" leads to error page when user is not logged in

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#57]
Steps to Reproduce:

1.  Open the test url: http://www.javul.org/
2. Click on ""Units""
3.Click on any user name from activity log
4.Click on ""Add funds""
5.Enter ""Amount to Donate"" and click on ""pay pal checkout"" and observe the error page.

Actual result:
Clicking on "pay pal checkout" leads to error page when user is not logged in.

Expected result:
Clicking on "pay pal checkout" should lead to pay pal page instead of error page.

Screenshot:  https://www.screencast.com/t/K0G2VDGE

**Comment by Motordread** [comment]
I found reason of error - script tries to send email like "You have donated" and "You have received a payment". It uses current authenticated user, as we try to send a payment without authentication we receive this error. How should we handle it? Should we even have ability to send payments as anonymous?

**Comment by javulorg** [comment]
Yea, anyone from outside the website (not a logged in user) can send payments into the website. I did that so people dont feel they have to make an account first in order to donate to their desired target (Unit, User or Objective etc).
I will try to make a Wiki page here on Github to show the Financial flows. It will be useful for testing too.

**Comment by javulorg** [comment]
I made the wiki page for Financial flows:
https://github.com/javulorg/javul/wiki/Financial-Flows
I'm not sure if 100% of this has been implemented or tested but the diagram shows the theory of how it should work. Feel free to edit that wiki page or create another issue for this.
When a not-logged-in user tries to donate, we want to ask them if they have a Javul account and want to login, or want to continue as an external user. Any donator should have the option of making their donation anonymous.
For Paypal I think they were using a Sandbox account. I have a Javul Paypal setup and we can link that link but for now we can keep using the Sandbox and set the default method to BitCoin.
For BitCoin I need to set up a Javul account but I think they might also have a Sandbox option for development. We can do testing of real fund transfers in the end.
The Financial flows and Task Management are going to be the more complex issues for this website which will need more testing/feature implementation.

**Comment by javulorg** [comment]
So the thing is that we want a non-logged user to donate to an existing User "A" of the site.
As for what the email activity should be:
If the user "A" has an email in their profile settings, we want to send them an email after the Paypal checkout is completed. "You have received a Payment of XYZ" (from person ABC).
Basically the user wants to know who the donator was, if the donator allows that information to be available. 
If the donator selects anonymous we can mention in the email: For this donation, the Donator chose to be anonymous".

These are the steps of the donation process that I'm thinking:

1. Click on Donate.
2. Page is shown for donation amount. Also let the user know "Note, Paypal will send some of your personal information such as your name, email address and address to the recipient. If you want to donate anonymously, please use our BitCoin option"
3. User is redirected to Paypal and they complete Checkout.
etc. I didnt think of the complete steps yet but something like this. We can work on it together later.

**Comment by javulorg** [comment]
For now we can focus on the main open issue for Financial flows: #66
