### ISSUE TITLE
Issue page: Link Issues

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#6]
http://javul.org/issues

1. On this page, the "Issue Title" should have links to the Issues so we can click and see the detail of that Issue.

2. Link to the Units does not work.

![image](https://cloud.githubusercontent.com/assets/19337355/21290741/f678609a-c493-11e6-927e-80be821972f5.png)

**Comment by acipher** [comment]
It should be fixed now. can you please check it?

**Comment by javulorg** [comment]
It works. Thanks.
