### ISSUE TITLE
Financial Functions

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#66]
Here's a simplified diagram of how the finances can work:

![image](https://user-images.githubusercontent.com/19337355/35489763-de277d40-0467-11e8-9543-53828bc59373.png)

We can see:
* A logged-in user or anonymous person can donate in different ways using Paypal. These flows are shown by Black arrows. Every Donation that comes in goes to the main Javul Paypal account. Donation can be made to a specific Unit, Objective or User. It can also be made into the General Purpose fund.
* Once that donation is completed, transfer of funds can be done internally using the red arrows. For these internal transfers Paypal is not involved. 
* Here is an example scenario: An anonymous user donates $100 to a Unit ABC using Paypal. What actually happens is that the money goes to Javul's main Paypal account. So now we have $100 in Javul's main Paypal account. In our database we record that $100 was donated to Unit ABC and the donation balance for Unit ABC is updated. From there we can assign $20 from the Unit's funds into a specific Objective that belongs to that Unit. The Objective can assign funds to a Task. When a user completes that tasks, they get an external payment using Paypal for completing that task. The $20 is transferred from the main Javul Paypal account to the user's Paypal account.

The following is the details for what happens when an anonymous user sends a donation to a Unit and a Unit's task is completed by a user:
1. User (not logged-in) clicks on "+" icon on a Unit's home page.
 2. They are shown a donation page that gives them an empty text box for the amount of donation to enter. Also show them a section that says "You can donate as an anonymous user or Login if you have an account". If the user is logged-in, they are given option to either donate anonymously or not. Anonymous means their username will not appear in the Global activity logs for the donation, only the amount and the Target unit.
3. When any donation happens, there is a line in the Activity log of the Unit that says "User ABC donated XYZ dollars". When a non-logged in user donates, or a logged-in user donates with the anonymous option, the 'user ABC' is replaced with "Anonymous" in the activity log.
4. After the amount is entered, they can click on "Pay with Paypal" and the API for Paypal is run.
5. For example if its $100 dollars, this money was transferred to Javul's main Paypal account.
6. The database for Unit ABC is updated so there is now $100 in Unit ABC's account.
7. Any user creates an Objective and assigns $30 to that objective. The available balance for the Unit is now $70. This is an internal transfer meaning there is no actual Paypal transaction involved.
8. Any user creates a Task and assigns it $20. This is also an internal transfer. The available balance for the Objective is now $10 (30-20).
9. Any user completes the task and now they need a Paypal transfer of $20 to their personal Paypal account. This will be an external transfer. The task is marked as complete. The user is shown the option to withdraw funds into their Paypal account.  The money goes from the Javul's main Paypal account to the user's Paypal account.

Other donation functions are similar. Donations can be made to an Objective and also to Javul's general purpose fund. If someone is donating but they dont know their specific target, they can just donate to the General purpose fund. From there funds can be transferred to other Units as needed.
Donations can also be made directly to a user. In this case the donation does not go through the Javul Paypal account. It goes directly to that user's Paypal address.

In order for a User to receive a donation they need to have a Paypal address in their account settings.

TASKS
These are some tasks related to resolving this issue:
- Test and implement donation to a user
- Items 7~9 (how funds are used by an Objective, task and are finally transferred to a User)

Later
- General purpose Javul fund so funds can be used for any purpose as necessary. This needs some more specifications in terms of database e.g. maybe special functions for the specific unit of Javul which enables us to transfer funds from that unit to any other unit.

**Comment by javulorg** [comment]
#57 and this issue can be resolved together (they are both dealing with finances). We will come back to this issue later and create some definition/specifications.

**Comment by Motordread** [comment]
Comment for me: https://developers.coinbase.com/

**Comment by javulorg** [comment]
Revised to exclude Bitcoin (due to high transaction fees). Now we're just using Paypal.

**Comment by javulorg** [comment]
I should have closed this before.
