### ISSUE TITLE
Create selection features for Units and Tasks pages

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#7]
Units page: http://javul.org/units
Allow to list all Units of a certain type e.g. by Location or Unit Category Type  (User can enter those fields and show results)

Similarly on Tasks page:
http://javul.org/tasks
Allow people to search by Task Skills and Status.

We dont need any selection features for Objectives and Issues page.

**Comment by acipher** [comment]
Units page: http://javul.org/units
Allow to list all Units of a certain type e.g. by Location or Unit Category Type (User can enter those fields and show results)

-> search by Location. do we need to show three different boxes for country, state and city?

**Comment by javulorg** [comment]
Sure that would be great (so just like the location interface for Unit creation).

**Comment by acipher** [comment]
created search feature for Task and Unit. can you please check?

**Comment by javulorg** [comment]
It works, thanks. Can you also add the "Browse" feature for the category, just like when we are trying to create a Unit? http://javul.org/units/add

**Comment by javulorg** [comment]
I think this is working now so I'm closing it.
