### ISSUE TITLE
Uploading Profile image throws "Internal Server Error"

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#70]
Steps to Reproduce:

1. Open the test url: http://www.javul.org/
2. Login with valid credentials.
3. Click on Account Settings.
4. Add Profile Image.
5. Click on Upload file and Verify.

Actual result:
Uploading Profile image throws "Internal Server Error".

Expected result:
Profile image should be uploaded with any error.

Screenshot: https://www.screencast.com/t/ooQCtt7oY2

**Comment by Motordread** [comment]
Thanks for report, issue was with missing GD library for PHP and missed permissions. I fixed it.
