### ISSUE TITLE
Unit Create Shows Error

### ISSUE THREAD

**Issue by acipher** [javulorg/javul#72]
When i create a new unit with country as "Global" and  it showed an error : [city_id cannot be null](https://trello-attachments.s3.amazonaws.com/5afecc218b6c6570b426f54b/5afecc39acba65ee1a97d697/566955838577a9fd58524bd360fec1ca/0unit.Creating_Unit-error.png)

To reproduce the issue : - Create new Unit and select country as "Global".

**Comment by acipher** [comment]
Should be fixed now,. Please check

**Comment by javulorg** [comment]
Closed.
