### ISSUE TITLE
Bid button does not show proper

### ISSUE THREAD

**Issue by acipher** [javulorg/javul#73]
If task has approval and there are no user logged on site so user can see bid now button instead of applied bid [attachment](https://trello-attachments.s3.amazonaws.com/5afecc218b6c6570b426f54b/5b054f50e216cb733cae7112/1744a027680898c5d6ca0f25e0ead3fd/bid_button_issue.png).

**Comment by acipher** [comment]
Should be fixed now. Please check

**Comment by javulorg** [comment]
Closed.
