### ISSUE TITLE
Task summary accept more than 1000 character

### ISSUE THREAD

**Issue by acipher** [javulorg/javul#75]
Task summary can accept 1000 or less character, now it have accept more than 1000 can you please check.
![image](https://user-images.githubusercontent.com/3071346/40775125-eafad386-64e4-11e8-9789-a26b207f98b1.png)

**Comment by Shivakumarbv** [comment]
@acipher @javulorg am getting emails from Git, am i expected to do anything?

**Comment by acipher** [comment]
Should be fixed now. Please review.

**Comment by javulorg** [comment]
Closing.
