### ISSUE TITLE
Task completion days show 30-days default

### ISSUE THREAD

**Issue by acipher** [javulorg/javul#76]
Wrong calculation of task completion days ,
Estimated Completion Time From : 2018/05/18 03:51 and 
Estimated Completion Time To : 2018/05/28 03:51 so Task completion time will be 10-days now it's show 30-day default.

![2 task_completion_date_issue](https://user-images.githubusercontent.com/3071346/40900060-6be1babe-67e7-11e8-9472-8c00066a6c14.png)

**Comment by acipher** [comment]
Fixed Please review.

**Comment by javulorg** [comment]
Closed
