### ISSUE TITLE
User cannot able to see task from "My Task" section

### ISSUE THREAD

**Issue by acipher** [javulorg/javul#78]
One task has assigned to user then user cannot able to see that task from "My task" section.

![click_on_task](https://user-images.githubusercontent.com/3071346/40900449-3d1f7b38-67e9-11e8-81a1-eb8d43a887c7.png)

![showing-404-error](https://user-images.githubusercontent.com/3071346/40900502-7cdadae2-67e9-11e8-9b24-3558d778dc15.png)

**Comment by acipher** [comment]
Fixed. Please check

**Comment by javulorg** [comment]
I didnt check but I trust that its fixed. Closed.
