### ISSUE TITLE
Tasks pages: Skills not showing up

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#8]
On Individual Task page (example), Task skill currently showing as ‘skill1, ‘skill2’ is not populated from the DB. Example: http://javul.org/tasks/1yjvmO9omn/test_t1

![image](https://cloud.githubusercontent.com/assets/19337355/21290753/9541b316-c494-11e6-820a-d40f8f635ced.png)

**Comment by acipher** [comment]
It should show now. can you please check it?

**Comment by javulorg** [comment]
It works but can you increase the font size of the skills so its the same size as the field above it (Status: Editable). Same size as "editable".

**Comment by javulorg** [comment]
To clarify, on this link:
http://javul.org/tasks/1yjvmO9omn/test_t1

The size of text in box '2' should be the same size as the text in box '1':

![image](https://cloud.githubusercontent.com/assets/19337355/22401011/bb393ab6-e592-11e6-9562-91367a8f4677.png)

**Comment by acipher** [comment]
I have changed font size. can you please check it

![change_font](https://cloud.githubusercontent.com/assets/3071346/22552204/f00e14ac-e97d-11e6-9995-5befd09018c8.png)
