### ISSUE TITLE
Unit Admin cannot edit task and task status

### ISSUE THREAD

**Issue by acipher** [javulorg/javul#83]
The task cannot be edited any further when the status changes to Approval. Only the Unit Admin can edit the task or change its status. Again, these actions are logged.

But now unit admin cannot see task edit button and  this case unit admin can change task status but now it cannot change task status.

![image](https://user-images.githubusercontent.com/3071346/40901959-e8911548-67ef-11e8-82f4-1e138d78bd26.png)

**Comment by javulorg** [comment]
For this issue, the admin does not need to edit the task if its in Approval state and any other state. Editing should only be possible for all users if the task is in 'Editable' status.

**Comment by acipher** [comment]
yes, unit admin not able to edit on approval state. Can you recheck and confirm?

**Comment by javulorg** [comment]
hi Anant, the Unit admin should not be able to edit, but they should still be able to change the task status if needed. For example they can change from "Open to Bidding" to "Editable". In that case the approval process for the tasks restarts from the beginning.
So you can check if the Unit Admin can change the task status or not. If yes then you can close this ticket.

**Comment by acipher** [comment]
Hi,

If i have created task and assigned it to user.

user has completed that task and it's in evaluation mode. now i want to change status of task from "completion evaluation" to "editable". 

What about the actions that are logged for previous actions that is task assignment, task completion, etc?

Do we need to remove that actions and consider it as not assigned task?

**Comment by javulorg** [comment]
Good questions. Yes for both of these:

> Do we need to remove that actions and consider it as not assigned task?

> or we need disable all other fields except task status while editing?

For the above, when the Unit Admin is logged in, you can show "Change Status" which then takes the admin to the Editing interface where they can only change the Task Status.

**Comment by acipher** [comment]
Now task admin can change status please review.

**Comment by javulorg** [comment]
Thanks, closing.
