### ISSUE TITLE
If one or more user edit task and submit for approval

### ISSUE THREAD

**Issue by acipher** [javulorg/javul#84]
Create new task and edit task by user TestAadhya and TestAadhya2. Now TestAadhya user submit for approval it will work properly.

After TestAadhya2 user submit task for approval it show toast message submitted request but task status will not change automatically need to refresh page.

![image](https://user-images.githubusercontent.com/3071346/40902478-bdebc8f4-67f1-11e8-9316-c589bd2d4488.png)

**Comment by acipher** [comment]
Fixed. Please check

**Comment by javulorg** [comment]
hi Anant, I'm unable to test this right now. But if you have checked it and you think its fixed you can close it.
