### ISSUE TITLE
If a user has edited that task and click on "Task Status: Editable (Submit for Approval)"

### ISSUE THREAD

**Issue by acipher** [javulorg/javul#85]
If user click on “Submit for Approval” is a link  it means they are done editing the task and think its ready for the next stage. If they are the only editor of the task so far, the task status will change to ‘Awaiting Approval’.

now task status changed but it shows "Approval" instead of ‘Awaiting Approval'

![image](https://user-images.githubusercontent.com/3071346/40903274-7d5c1dc2-67f4-11e8-996f-7e89d0da826a.png)

after submitting

![image](https://user-images.githubusercontent.com/3071346/40903314-960ab270-67f4-11e8-9895-ed8ea4a5a407.png)

**Comment by acipher** [comment]
Question:

With single editor, when we show "Awaiting Approval" status, do we need to wait for 7 days to change its status to "Approval"?

**Comment by javulorg** [comment]
Good question. No, if its a single editor, no wait is needed. So when they do 'submit for approval', its next status becomes "Open for Bidding".

**Comment by acipher** [comment]
Done please review.

**Comment by javulorg** [comment]
I'm not able to check but I trust its fixed, so closing.
