### ISSUE TITLE
User-1 is able to edit another user's Wiki page successfully.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#86]
Environment :- Windows 7
Module :- User Wiki
Credentials :- r6.pulsefbi@gmail.com
Priority :- Critical

Steps to reproduce :- 
1.Open Javul Site and login with given credentials.
2.Navigate to home page.
3.Select any user under Global Activity.
4.Scroll down and click on Edit, under USER WIKI.
5.Enter valid data and click on Save and observe.

Actual Result :- User-1 is able to edit another user's Wiki page successfully and Confirmation message is also displayed.
Expected Result :- User-1 should not have access to edit another user's Wiki page. 

Video URL :- https://drive.google.com/file/d/16K5C2xoyY7hhKKiIoZE715X5yDSibJCS/view?usp=sharing

**Comment by javulorg** [comment]
I think this is ok as Default behavior, but I would like to see an option in the User Settings where they can set their Wiki to be editable by the public or not. This is how it can be displayed:
"Let others edit your Wiki pages?" Yes / No  (set to Yes by default)

When set to 'No', other people should not see the 'edit' link for any User wiki page that has that permission set. They should also not be able to add new pages to that Users wiki. And at the time of saving a wiki page, this permission should be checked.

**Comment by acipher** [comment]
#94 fixed please check and review.

**Comment by acipher** [comment]
@Shivakumarbv and @javulorg can you please test this issue.

**Comment by javulorg** [comment]
I'll close this for now as the desired default behavior is working now (I assume).

I'll make a note to revisit this later for the other functionality I mentioned above.
