### ISSUE TITLE
When clicked on 'About This Site', 'FAQ', 'How Can I Help', 'Javul.Org Unit', user is not navigated to any of these pages.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#87]
Environment :- Windows 7
Module :- Home Page
Credentials :- john_k@gmail.com/11111111
Priority :- Critical

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page.
3.Click on 'About This Site', 'FAQ', 'How Can I Help', 'Javul.Org Unit' and observe.

Actual Result :- When clicked on 'About This Site', 'FAQ', 'How Can I Help', 'Javul.Org Unit', user is not navigated to any of these pages.
Expected Result :- When clicked on 'About This Site', 'FAQ', 'How Can I Help', 'Javul.Org Unit', Respected page should be displayed.

Video URL :- https://drive.google.com/file/d/1820zIIkZVhismQGZfJJEVbak3Os5LvGy/view?usp=sharing

**Comment by javulorg** [comment]
Moved into #105
