### ISSUE TITLE
User is not able to redirect to login page with successful logout.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#88]
Environment :- Windows 7
Module :- Login
Credentials :- john_k@mailinator.com/11111111
Priority :- High

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page.
3 Click on logout
4 Observe.

Actual Result :- user is not able to redirect to login page with successful logout.
 Expected Result :- User should able to rediect to login page with successful logout.

 Video URL:https://drive.google.com/file/d/1TPDZqyEct1FEYJEUmQsTpMfYOftpSHBh/view?usp=sharing

**Comment by acipher** [comment]
Done please check and review.

**Comment by acipher** [comment]
After successful logout user will redirect to login screen.

**Comment by javulorg** [comment]
Actually after logout, can we redirect to the home page? www.javul.org

**Comment by acipher** [comment]
In above ticket description he say we want to redirect user to login page, so now can you please confirm that what we have to do it will redirect **Home Page or Login Page**?. Please confirm.
