### ISSUE TITLE
When clicked on "Forgot Password" and requested for "Password Reset Link", "We have e-mailed your password reset link!" message is displayed. But, user is not receiving any link through email.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#89]
Environment :- Windows 7
Module :- Forgot Password
Credentials :- r6.pulsefbi@gmail.com
Priority :- Critical

Steps to reproduce :-
1.Open Javul Site and navigate to login page.
2.Click on Forgot Password and valid Email ID.
3.Click on "Send Password Reset Link".
4.Open inbox of given email ID and observe.

Actual Result :- When clicked on "Forgot Password" and requested for "Password Reset Link", "We have e-mailed your password reset link!" message is displayed. But, user is not receiving any link through email. 
Expected Result :- When clicked on "Forgot Password" and requested for "Password Reset Link", "We have e-mailed your password reset link!" message is displayed. But, user is not receiving any link through email.

Video URL :- https://drive.google.com/file/d/1I5aCPDgFp836Tx8MANXujPy0NBozPujv/view?usp=sharing

**Comment by acipher** [comment]
Now user can able to receive reset password email link can you please check and confirm.

**Comment by javulorg** [comment]
hi Anant, sure you can close this if you can receive email now. If there was any server setup involved, can we add those directions to the Server setup page? https://github.com/javulorg/javul/wiki/Setting-up-on-a-new-Webhost-and-Working-with-Existing-Code
Let me know if there's a Linode link for this or something else that we can add there.

**Comment by acipher** [comment]
Description added on server setup page.
