### ISSUE TITLE
Unit Pages: Show some database fields

### ISSUE THREAD

**Issue by javulorg** [javulorg/javul#9]
On Individual Unit page, some fields need to be shown for example, Unit Credibility can be shown after ‘Unit Location’ field. Related Units, Parent Units can be shown at the end of the Unit page (Edit any unit to see these fields).

http://javul.org/units/4wnY7egoOW/human_rights

![image](https://cloud.githubusercontent.com/assets/19337355/21290767/24a626d6-c495-11e6-8a18-b142d9e41a22.png)

**Comment by acipher** [comment]
Changed the order of fields as mentioned  in edit unit page. Can you please check? 

Let me know if need to change.

**Comment by javulorg** [comment]
Looks fine except for "credibility" that is currently showing location:
http://javul.org/units/4wnY7egoOW/human_rights
![image](https://cloud.githubusercontent.com/assets/19337355/23239452/5976875a-f935-11e6-972e-2cd25425493a.png)

**Comment by acipher** [comment]
Shown "Unit Credibility" value on mentioned place. Please review.

**Comment by javulorg** [comment]
Thanks, closed.
