### ISSUE TITLE
When enabled 'Default All', all the options are enabled, except "Account creation", "Confirmation email".

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#90]
Environment :- Windows 7
Module: Profile
Credentials :- john_k@mailinator.com/11111111
Priority :- High

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page.
3 Click on account settings.
4 Click on alert settings
5 Now enable Default All and observe.

Actual result: When enabled 'Default All', all the options are enabled, except "Account creation", "Confirmation email".
Expected result: When clicked on "default all", All the options should be enabled.

Video URL:https://drive.google.com/open?id=1_7eUyGZe9mT8-zztQ3iBD6Dsh7Q1-GCK

**Comment by acipher** [comment]
For the options of **Account creation", "Confirmation email** i found the default value **1** in database it mean default is on. So @javulorg can you confirm if we need this way? or keep it as is without change?

**Comment by javulorg** [comment]
I'll think about this to see how this should work.

**Comment by javulorg** [comment]
Ok, I checked this. Remove these three buttons: Default All, Account Creation, and Confirmation Email

When a new account is made, the remaining options should be on by default.

I'll think about Confirmation/account creation email and will make another ticket for it later.

**Comment by acipher** [comment]
Above three option are removed and other options are set as default on. can you please check and review.

![image](https://user-images.githubusercontent.com/3071346/53326137-d7884900-390a-11e9-9e29-b15e40548295.png)

**Comment by javulorg** [comment]
Sure, looks good, I'll close this.
