### ISSUE TITLE
When user click on "Recent Changes" and "List All Pages", error message is displayed as "Whoops, looks like something went wrong." "ErrorException".

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#91]
Environment :- Windows 7
Module :- My Profile / User Wiki
Credentials :- r6.pulsefbi@gmail.com
Priority :- High

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Click on My Profile and scroll down.
3.Click on "Recent Changes" under User Wiki and observe.
4.Click back and Click on "List All Pages" under User Wiki and observe.

Actual Result :- When user click on "Recent Changes" and "List All Pages", error message is displayed as "Whoops, looks like something went wrong." "ErrorException".
Expected Result :- When user click on "Recent Changes" and "List All Pages", error message should not be displayed. Respected pages should be displayed.

Video URL :- https://drive.google.com/file/d/1y_AqriTLzjFv5SmxxWiwktVw-yNhyMi3/view?usp=sharing

**Comment by acipher** [comment]
Fixed please check and review.
