### ISSUE TITLE
When the user enters space in search field "white spaces are not allowed" error message is not displaying.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#92]
Environment :- Windows 7
Module: Search
Credentials :- john_k@mailinator.com/11111111
Priority :- Low

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page.
3.Go to search field
4 Enter space in search field 
5 Observe

Actual result : When the user enters space in search field "white spaces are not allowed" error messageis not displaying.
Expected result: "white spaces are not allowed" error message should be display.

Video URL:https://drive.google.com/open?id=1VGi0Wahxi678uFuuVvV6FNrQYpzP5xQi

**Comment by acipher** [comment]
Added info message when trying to search with white space.
Please check and review.

**Comment by acipher** [comment]
Done can you please check below attachment.
[https://drive.google.com/file/d/1Zz58Hl8ZFxmUKQSDQJXX4R3eIkqVAvsB/view?usp=sharing](https://drive.google.com/file/d/1Zz58Hl8ZFxmUKQSDQJXX4R3eIkqVAvsB/view?usp=sharing)
