### ISSUE TITLE
When user create his User Wiki page, error message is displayed as   "Whoops, looks like something went wrong." "ErrorException". 

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#94]
Environment :- Windows 7
Module :- My Profile / User Wiki
Credentials :- r6.pulsefbi@gmail.com
Priority :- High

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Click on MyProfile and scroll down.
3.Click on New Page and Enter valid data in all the fields.
4.Click on Save Page and observe.

Actual Result :- When user create his User Wiki page, error message is displayed as   "Whoops, looks like something went wrong." "ErrorException". 
Expected Result :- When user create his User Wiki page, error message should not be displayed. 

Video URL :- https://drive.google.com/file/d/1ZSxQWql0b32YvDHamkbdkkjClSuK_qd7/view?usp=sharing

**Comment by acipher** [comment]
Fixed please check and review.
