### ISSUE TITLE
Address field is expandable and when entered valid data, The data is overlapped by 'Job skills' and 'Areas of Interest'.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#95]
Environment :- Windows 7
Module :- Account Settings
Credentials :- r6.pulsefbi@gmail.com
Priority :- Medium

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Click on "Account Settings" and scroll down.
3.Expand the address field and valid data and observe.

Actual Result :- Address field is expandable and when entered valid data, The data is overlapped by 'Job skills' and 'Areas of Interest'.
Expected Result :- Address field should not be expandable, in such a way that other fields can be overlapped on it and when entered valid data, The data should not be overlapped by 'Job skills' and 'Areas of Interest'.

Video URL :-  https://drive.google.com/file/d/1owHfxmiOKMA9d2Mu88eV-KY-VkA9h5Lj/view?usp=sharing

**Comment by acipher** [comment]
Closing this ticket with attachment of video.

[https://drive.google.com/file/d/1WBBQ3uNjh33_ufMjcOv6HWOQPriz__uN/view?usp=sharing](https://drive.google.com/file/d/1WBBQ3uNjh33_ufMjcOv6HWOQPriz__uN/view?usp=sharing)
