### ISSUE TITLE
Confirmation message is not displaying when user edit the "units"

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#96]
Environment :- Windows 7
Module :- Unit
Credentials :- john_k@mailinator.com/11111111
Priority :- Low

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page.
3. Search for created unit(Hardware)
4. click on hardware
5 Click on edit(hardware)
6 It will navigate to edit unit
7 Do some change
8 Do some change click on Update.
9 Observe
('Your details have been saved' confirmation message is not displaying.)

Actual result: Confirmation message is not displaying when the user edit  the "units"
Expected result: Confirmation message should be displayed  when the user edit  the "units"

Video URL: https://drive.google.com/open?id=17r4yTfd_Tg-HS6Ri6YgJZXSDrtfn9AnN

**Comment by acipher** [comment]
Done please check and review.
