### ISSUE TITLE
After logout, when user click back, Login Page is not displayed and user's personal info is displayed.

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#97]
Environment :- Windows 7
Module :- Logout
Credentials :- r6.pulsefbi@gmail.com
Priority :- High

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Click on MyProfile/Account Settings.
3.Click on Logout and click back and observe.

Actual Result :- After logout, when user click back, Login Page is not displayed and user's personal info is displayed.
Expected Result :- After logout, when user click back, Login Page should be displayed.

Video URL :- https://drive.google.com/file/d/1eMFDVaieTJ3LOGDNIVHa-wZOwZPgtlsM/view?usp=sharing

**Comment by acipher** [comment]
It is not showing users personal info page it will showing last page of before you logout from site and it will be showing from browser cache. You cannot able change anything in any form please let me know what i have to do.

**Comment by acipher** [comment]
After successfully logout user will redirect to Login page.  @javulorg can you please check and confirm.

**Comment by javulorg** [comment]
Yes I remember this was fixed and I tested it now and this issue doesnt show up now. Closing this, tanks.
