### ISSUE TITLE
When user click on "ADD ISSUE", error message is displayed as "Whoops, looks like something went wrong." "ErrorException".

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#98]
Environment :- Windows 7
Module: Units
Credentials :- john_k@mailinator.com/11111111
priority : Critical

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Navigate to home page.
3.Click on units
4.Click on any created Unit
5 In unit information click on "ADD ISSUE"
6 Observe

Actual result:When user click on "ADD ISSUE", error message is displayed as "Whoops, looks like something went wrong." "ErrorException".
Expected result: When user click on "ADD ISSUE", error message should not be displayed.

**Comment by acipher** [comment]
Fixed please check and review.
