### ISSUE TITLE
When clicked on Unit category name, under Unit Categories, error message is displayed as "Whoops, looks like something went wrong." "Error Exception".

### ISSUE THREAD

**Issue by Shivakumarbv** [javulorg/javul#99]
Environment :- Windows 7
Module :- Units
Credentials :- r6.pulsefbi@gmail.com
Priority :- High

Steps to reproduce :-
1.Open Javul Site and login with given credentials.
2.Click on Units and select any unit.
3.Again click on unit category name under Unit Category and observe.

Actual Result :- When clicked on Unit category name, under Unit Categories, error message is displayed as "Whoops, looks like something went wrong." "Error Exception".
Expected Result :- When clicked on Unit category name, under Unit Categories, error message should not be displayed.

Video URL :- https://drive.google.com/file/d/1AFzXXjibowYkCO8oybPzdE8Ywvk7o2JO/view?usp=sharing

**Comment by acipher** [comment]
We do not have any screen related unit category so @javulorg  can you please confirm what we have to do in this ticket.

**Comment by javulorg** [comment]
hi Anant, what I want to see for that view is all the Units which have that category which was clicked. You can use this as the page's headline: Units with the Category: XYZ
In that view we can have hyperlinks to all the Unit's home pages.

**Comment by acipher** [comment]
Done please review.

**Comment by acipher** [comment]
Closing this ticket with attachment of video.
[https://drive.google.com/file/d/1livJyUnGcCJEJ39VF0uYSpOAJf2A6sD5/view?usp=sharing](https://drive.google.com/file/d/1livJyUnGcCJEJ39VF0uYSpOAJf2A6sD5/view?usp=sharing)
